using System;
using System.Collections.Generic;
using System.Windows;

namespace TerminalLauncher.Services;

/// <summary>لغة الواجهة.</summary>
public enum AppLang { Ar, En }

/// <summary>
/// تعريب بسيط وقت التشغيل (عربي/إنجليزي) + اتجاه الواجهة (RTL/LTR).
/// القيم مُضمّنة كأزواج (عربي، إنجليزي)؛ الطبقات تستدعي <see cref="T"/> بمفتاح.
/// </summary>
public static class Loc
{
    public static AppLang Current { get; private set; } = AppLang.Ar;

    /// <summary>يُطلَق عند تغيّر اللغة (تُعيد الطبقات تطبيق النصوص/الاتجاه).</summary>
    public static event Action? Changed;

    /// <summary>اتجاه الواجهة الموافق للّغة الحاليّة.</summary>
    public static FlowDirection Flow => Current == AppLang.Ar ? FlowDirection.RightToLeft : FlowDirection.LeftToRight;

    /// <summary>رمز اللغة للحفظ ("ar"/"en").</summary>
    public static string Code => Current == AppLang.En ? "en" : "ar";

    /// <summary>يضبط اللغة من رمز محفوظ دون إطلاق الحدث (للتهيئة).</summary>
    public static void InitFromCode(string? code)
        => Current = string.Equals(code, "en", StringComparison.OrdinalIgnoreCase) ? AppLang.En : AppLang.Ar;

    /// <summary>يبدّل اللغة ويُطلِق <see cref="Changed"/>.</summary>
    public static void Set(AppLang lang)
    {
        if (Current == lang) return;
        Current = lang;
        Changed?.Invoke();
    }

    /// <summary>النصّ الموافق للّغة الحاليّة (يعيد المفتاح نفسه إن لم يُعرَّف).</summary>
    public static string T(string key)
        => Table.TryGetValue(key, out var pair) ? (Current == AppLang.En ? pair.En : pair.Ar) : key;

    private static readonly Dictionary<string, (string Ar, string En)> Table = new()
    {
        ["app.title"]          = ("مشغّل الأوامر", "Command Launcher"),
        // شاشة البدء: سطر المرحلة الجارية تحت العلامة (تتغيّر مع تقدّم الإقلاع).
        ["splash.starting"]    = ("جارٍ التشغيل…", "Starting…"),
        ["splash.data"]        = ("تحميل الأوامر والمشاريع…", "Loading commands and projects…"),
        ["splash.ui"]          = ("تجهيز الواجهة…", "Preparing the interface…"),
        ["splash.session"]     = ("استعادة الجلسة السابقة…", "Restoring your session…"),

        // قائمة «+» حين لا يوجد تيرمنال مفتوح يُورَّث مجلده: أماكن بدء مقترَحة.
        // نقطة حالة التنفيذ في رأس التبويب (تلميح عند المرور).
        ["tab.state.running"]  = ("يعمل الآن…", "Running…"),
        ["tab.state.done"]     = ("انتهى بنجاح", "Finished successfully"),
        ["tab.state.failed"]   = ("انتهى بخطأ", "Finished with an error"),

        ["paths.title"]        = ("افتح تيرمنال في…", "Open a terminal in…"),
        ["paths.desktop"]      = ("سطح المكتب", "Desktop"),
        ["paths.documents"]    = ("المستندات", "Documents"),
        ["paths.downloads"]    = ("التنزيلات", "Downloads"),
        ["paths.home"]         = ("مجلد المستخدم", "Home folder"),
        ["paths.browse"]       = ("استعراض مجلد…", "Browse for a folder…"),
        ["sidebar.saved"]      = ("الأوامر المحفوظة", "Saved commands"),
        ["sidebar.search"]     = ("بحث…", "Search…"),
        ["btn.run"]            = ("▶  تشغيل", "▶  Run"),
        ["hint.pick"]          = ("اختر أمراً واضغط «تشغيل» لفتح تيرمنال", "Pick a command and press Run to open a terminal"),
        // لوحة البداية: عنوان + وصف كلّ اختصار بجوار رقاقاته.
        ["hint.title"]         = ("جلسة تيرمنال جديدة", "New terminal session"),
        ["hint.palette"]       = ("لوحة الأوامر", "command palette"),
        ["hint.splitV"]        = ("انقسام جنباً لجنب", "split side by side"),
        ["hint.splitH"]        = ("انقسام فوق/تحت", "split top/bottom"),
        ["sidebar.projects"]   = ("المشاريع", "Projects"),
        // يُعرض بجوار رقاقات الكيبورد (ctrl shift T) فلا يذكر الاختصار نصّاً.
        ["hint.empty"]         = ("تيرمنال فارغ", "new empty terminal"),
        // النصّ البديل في حقل البحث المركزيّ بشريط العنوان (يفتح لوحة البحث المتقدّم).
        ["hdr.search"]         = ("ابحث في كل شيء…", "Search everything…"),

        // لوحة البحث المتقدّم: عناوين الأقسام ورقاقات الفئات.
        ["palette.suggested"]  = ("مقترَح", "Suggested"),
        ["palette.results"]    = ("النتائج ({0})", "Results ({0})"),
        ["palette.cat.actions"]  = ("أفعال", "actions"),
        ["palette.cat.projects"] = ("مشاريع", "projects"),
        ["palette.cat.commands"] = ("أوامر", "commands"),
        ["palette.cat.tabs"]     = ("تبويبات", "tabs"),
        ["palette.cat.shells"]   = ("صدفات", "shells"),
        ["settings.title"]     = ("الإعدادات", "Settings"),
        ["settings.appearance"]= ("المظهر", "Appearance"),
        ["settings.theme"]     = ("الثيم", "Theme"),
        ["settings.themehint"] = ("اختر ثيماً — يُطبَّق فوراً", "Pick a theme — applied instantly"),
        ["settings.showAllThemes"] = ("عرض كل الثيمات", "Show all themes"),
        ["settings.allThemes"] = ("كل الثيمات", "All themes"),
        ["tip.toggleSidebar"]  = ("إظهار/إخفاء الأوامر المحفوظة", "Show/hide saved commands"),
        ["settings.syncos"]    = ("مزامنة الفاتح/الداكن مع النظام", "Sync light/dark with OS"),
        ["settings.dark"]      = ("داكن", "Dark"),
        ["settings.light"]     = ("فاتح", "Light"),
        ["settings.accent"]    = ("لون التمييز", "Accent color"),
        ["settings.fontsize"]  = ("حجم خطّ التيرمنال", "Terminal font size"),
        ["settings.fontfamily"]= ("نوع الخطّ", "Font family"),
        ["settings.terminalFont"] = ("خطّ الطرفية (التيرمنال)", "Terminal font"),
        ["settings.uiFonts"]   = ("خطوط الواجهة", "Interface fonts"),
        ["settings.uiFamily"]  = ("خطّ الواجهة (اسم خطّ مثبَّت — فارغ = الافتراضيّ)", "UI font (installed font name — blank = default)"),
        ["settings.monoFamily"]= ("الخطّ أحاديّ العرض (المسارات/النصوص التقنيّة)", "Monospace font (paths / technical text)"),
        ["settings.uiSize"]    = ("حجم نصّ الواجهة", "UI text size"),
        ["settings.menuSize"]  = ("حجم القوائم", "Menu size"),
        ["settings.tableSize"] = ("حجم الجداول", "Table size"),
        ["settings.titleSize"] = ("حجم العناوين", "Title size"),
        ["settings.smallSize"] = ("حجم النصّ الثانويّ (التلميحات والشارات)", "Secondary text size (hints and badges)"),
        ["ai.cmp.model"]       = ("نموذج هذه الجلسة", "Model for this session"),
        ["ai.cmp.noModel"]     = ("اختر نموذجاً", "Pick a model"),
        ["ai.cmp.pickTitle"]   = ("النماذج المتوفّرة", "Available models"),
        ["ai.cmp.pickSearch"]  = ("gemma", "gemma"),
        ["ai.cmp.pickApply"]   = ("اعتماد", "Use this"),
        ["ai.cmp.pickLoading"] = ("جارٍ جلب القائمة…", "Fetching the list…"),
        ["ai.cmp.pickNone"]    = ("تعذّر جلب قائمة النماذج — تأكّد من المزوّد والمفتاح في الإعدادات.",
                                  "Could not fetch the model list — check the provider and key in settings."),
        ["ai.cmp.pickNoMatch"] = ("لا نموذج يطابق البحث.", "No model matches the search."),
        ["ai.cmp.pickCount"]   = ("{0} من {1} نموذجاً", "{0} of {1} models"),
        ["ai.cmp.freeBadge"]   = ("مجّانيّ", "free"),
        ["settings.roles"]     = ("أحجام تفصيليّة", "Detailed sizes"),
        ["settings.rolesHint"] = ("لكلّ نوع نصّ في التطبيق دورٌ وحجم. هذه الأدوار تتبع «حجم نصّ الواجهة» تلقائيّاً — أطفئ التتبّع لتضبط كلّ واحد وحده.",
                                  "Every kind of text in the app has a role and a size. These roles follow the interface text size automatically — turn that off to set each one yourself."),
        ["settings.rolesAuto"] = ("اشتقّها من حجم نصّ الواجهة", "Derive them from the interface text size"),
        ["settings.headingSize"] = ("عناوين فرعيّة", "Sub-headings"),
        ["settings.tinySize"]  = ("النصّ الدقيق (الشارات والعدّادات)", "Fine print (badges and counters)"),
        ["settings.codeSize"]  = ("النصّ التقنيّ (المسارات والكود)", "Technical text (paths and code)"),
        ["settings.displaySize"] = ("النصّ الكبير (حالات الفراغ)", "Large text (empty states)"),
        ["settings.smallAuto"] = ("تلقائيّ (يتبع حجم نصّ الواجهة)", "Automatic (follows UI text size)"),
        ["settings.pickFont"]  = ("اختر من الخطوط المثبَّتة أو اكتب اسماً — فارغ = الافتراضيّ", "Pick an installed font or type a name — blank = default"),
        ["settings.openJson"]  = ("فتح ملف الإعدادات (JSON)", "Open settings file (JSON)"),
        ["settings.editConfig"] = ("محرّر الإعدادات", "Config editor"),
        ["settings.applyJson"] = ("إعادة تحميل الملف", "Reload file"),
        ["settings.resetFont"] = ("استعادة الافتراضي", "Reset to default"),
        ["settings.cornerRadius"] = ("استدارة الحواف", "Corner radius"),
        ["settings.fontsHint"] = ("تُحفَظ في config.json وتُطبَّق فوراً. استعمل «محرّر الإعدادات» للتعديل بأمان.", "Saved to config.json and applied instantly. Use the Config editor to edit safely."),
        // ===== محرّر الإعدادات الذكيّ =====
        ["cfg.title"]          = ("محرّر الإعدادات", "Config editor"),
        ["cfg.tab.ui"]         = ("الواجهة (config.json)", "Interface (config.json)"),
        ["cfg.tab.system"]     = ("النظام", "System"),
        ["cfg.format"]         = ("تنسيق", "Format"),
        ["cfg.validate"]       = ("تحقّق", "Validate"),
        ["cfg.save"]           = ("حفظ وتطبيق", "Save & apply"),
        ["cfg.reload"]         = ("إعادة تحميل", "Reload"),
        ["cfg.close"]          = ("إغلاق", "Close"),
        ["cfg.valid"]          = ("صياغة سليمة ✓", "Valid syntax ✓"),
        ["cfg.saved"]          = ("حُفِظ وطُبِّق ✓", "Saved & applied ✓"),
        ["cfg.savedRestart"]   = ("حُفِظ ✓ — أعد التشغيل لتطبيق إعدادات النظام", "Saved ✓ — restart to apply system settings"),
        ["cfg.formatted"]      = ("نُسِّق ✓", "Formatted ✓"),
        ["cfg.errAt"]          = ("خطأ عند السطر {0}، العمود {1}: {2}", "Error at line {0}, column {1}: {2}"),
        ["cfg.errSave"]        = ("تعذّر الحفظ: {0}", "Save failed: {0}"),
        ["cfg.cantSaveInvalid"] = ("لا يمكن الحفظ: صحّح أخطاء الصياغة أوّلاً", "Cannot save: fix syntax errors first"),
        ["cfg.systemHint"]     = ("إعدادات النظام (الثيم/اللغة/الخلفية). تُطبَّق بعد إعادة التشغيل.", "System settings (theme/language/background). Applied after restart."),
        ["settings.textcolor"] = ("لون الكتابة", "Text color"),
        ["settings.language"]  = ("اللغة", "Language"),
        ["settings.background"] = ("الخلفية", "Background"),
        ["settings.font"]       = ("الخطّ", "Font"),
        ["settings.appearanceBg"] = ("المظهر والخلفية", "Appearance & Background"),
        ["settings.langFont"]     = ("اللغة والخطّ", "Language & Font"),
        ["settings.autosave"]  = ("تُحفظ التفضيلات تلقائياً", "Preferences are saved automatically"),

        // ===== الخلفيّة (قوالب + صورة + شفافيّة التيرمنال) =====
        ["bg.section"]         = ("الخلفية", "Background"),
        ["bg.templates"]       = ("قوالب", "Templates"),
        ["bg.solids"]          = ("ألوان مصمتة", "Solid colors"),
        ["bg.gradients"]       = ("تدرّجات", "Gradients"),
        ["bg.patterns"]        = ("نقوش", "Patterns"),
        ["bg.themeDefault"]    = ("خلفية الثيم", "Theme default"),
        ["bg.custom"]          = ("صورة مخصّصة", "Custom image"),
        ["bg.choose"]          = ("اختر صورة", "Choose image"),
        ["bg.clear"]           = ("إزالة", "Remove"),
        ["bg.opacity"]         = ("شفافية التيرمنال", "Terminal opacity"),
        ["tip.newtab"]         = ("تيرمنال فارغ جديد (Ctrl+Shift+T)", "New empty terminal (Ctrl+Shift+T)"),
        ["tip.history"]        = ("سجلّ الأوامر", "Command history"),
        ["tip.settings"]       = ("الإعدادات", "Settings"),
        // وسوم نوع الاقتراح في صندوق التأليف (تُعرَض كحبّة صغيرة يمين كلّ عنصر).
        ["sug.command"]        = ("أمر", "command"),
        ["sug.subcommand"]     = ("أمر فرعيّ", "subcommand"),
        ["sug.flag"]           = ("خيار", "flag"),
        ["sug.folder"]         = ("مجلد", "folder"),
        ["sug.file"]           = ("ملفّ", "file"),
        ["sug.branch"]         = ("فرع", "branch"),
        ["sug.script"]         = ("سكربت", "script"),
        ["sug.process"]        = ("عمليّة", "process"),
        ["sug.history"]        = ("سجلّ", "history"),
        ["sug.alias"]          = ("أمر مختصر", "alias"),
        // متصفّح المجلدات (زرّ الباث فوق الإنبت).
        ["cwd.parent"]         = (".. (المجلد الأعلى)", ".. (Parent Directory)"),
        ["cwd.search"]         = ("ابحث في المجلدات…", "Search directories…"),
        ["tip.cwdPicker"]      = ("تصفّح المجلدات (cd)", "Browse folders (cd)"),
        ["tip.add"]            = ("إضافة أمر", "Add command"),
        ["profiles.manage"]    = ("إدارة البروفايلات…", "Manage profiles…"),
        // {0} = العدد الكلّيّ للصدفات المتاحة.
        ["profiles.showAll"]   = ("عرض كل الصدفات ({0})…", "Show all shells ({0})…"),

        // ===== تأكيد اللصق (حماية) =====
        ["paste.title"]        = ("تأكيد اللصق", "Confirm paste"),
        ["paste.warnMulti"]    = ("أنت على وشك لصق نصّ متعدّد الأسطر في التيرمنال. راجعه قبل التنفيذ:",
                                  "You are about to paste multi-line text into the terminal. Review it before running:"),
        ["paste.warnDanger"]   = ("⚠ يحتوي النصّ الملصوق على أوامر قد تكون خطرة. راجعه بعناية قبل اللصق:",
                                  "⚠ The pasted text contains commands that may be dangerous. Review it carefully before pasting:"),
        ["paste.confirm"]      = ("لصق", "Paste"),
        ["paste.cancel"]       = ("إلغاء", "Cancel"),
        ["paste.lines"]        = ("سطر", "lines"),

        // ===== لوحة «ما الجديد» (What's New) =====
        ["whatsnew.title"]     = ("ما الجديد", "What's New"),
        ["whatsnew.empty"]     = ("لا توجد مستجدّات لعرضها.", "No changes to show yet."),
        ["whatsnew.highlights"]= ("أبرز المميّزات", "Highlights"),
        ["whatsnew.section.new"]      = ("جديد", "New"),
        ["whatsnew.section.improved"] = ("تحسينات", "Improved"),
        ["whatsnew.section.fixed"]    = ("إصلاحات", "Fixed"),
        ["tip.whatsnew"]       = ("ما الجديد / حول البرنامج", "What's New / About"),
        ["common.close"]       = ("إغلاق", "Close"),

        // ===== لوحة المشاريع + الدوك =====
        ["sidebar.projects"]   = ("المشاريع", "Projects"),
        ["proj.open"]          = ("تيرمنال جديد", "New terminal"),
        ["proj.openTip"]       = ("تيرمنال جديد على باث المشروع المحدَّد (أو فارغ إن لا تحديد)",
                                  "New terminal at the selected project's path (empty if none selected)"),
        ["proj.search"]        = ("بحث في المشاريع…", "Search projects…"),
        ["proj.new"]           = ("مشروع جديد", "New project"),
        ["proj.edit"]          = ("تعديل المشروع", "Edit project"),
        ["proj.noFolder"]      = ("بلا فولدر — اضغط لتحديده", "No folder — click to set"),
        ["proj.steps"]         = ("خطوات", "steps"),
        ["proj.field.name"]    = ("الاسم", "Name"),
        ["proj.field.tags"]    = ("التاكات (تصنيفات ملوّنة)", "Tags (colored labels)"),
        ["proj.field.folder"]  = ("الباث (مجلّد العمل)", "Path (working directory)"),
        ["proj.filter.all"]    = ("الكل", "All"),
        ["proj.noTags"]        = ("لا تاكات بعد — أنشئ تاكاً بالأسفل", "No tags yet — create one below"),
        ["proj.field.shell"]   = ("الصدفة الافتراضية", "Default shell"),
        ["proj.folder.browse"] = ("اختر الفولدر", "Choose folder"),
        ["proj.cmd.new"]       = ("＋ أمر جديد", "＋ New command"),
        ["proj.cmd.edit"]      = ("تعديل الأمر", "Edit command"),
        ["proj.cmd.labelHint"] = ("اسم الأمر (اختياريّ)", "Command name (optional)"),
        ["proj.cmd.stepsHint"] = ("أمر في كلّ سطر — تُنفَّذ بالتوالي", "One command per line — run in sequence"),
        ["proj.cmd.folderHint"]= ("فولدر خاصّ (اختياريّ) — نسبيّ يُدمج مع باث المشروع",
                                  "Override folder (optional) — a relative path merges with the project path"),
        ["proj.cmd.terminal"]  = ("افتح تيرمنال على باث الأمر (بلا تنفيذ)",
                                  "Open a terminal at the command's path (without running it)"),
        ["proj.folderMissing"] = ("الفولدر «{0}» غير موجود — فُتح التيرمنال على باث المشروع.",
                                  "Folder “{0}” does not exist — opened at the project path instead."),
        // ليبلات محرّر الأمر المضمّن (فوق كلّ حقل).
        ["proj.cmd.labelLbl"]  = ("الاسم", "Name"),
        ["proj.cmd.stepsLbl"]  = ("الأوامر", "Commands"),
        ["proj.cmd.folderLbl"] = ("الفولدر", "Folder"),
        ["quick.addCurrent"]   = ("＋ أضف الأمر الحاليّ من التيرمنال", "＋ Add current command from terminal"),
        ["quick.remove"]       = ("حذف الأمر", "Remove command"),
        ["quick.noSteps"]      = ("اكتب أمراً واحداً على الأقلّ في خانة «الأوامر».",
                                  "Type at least one command in the Commands field."),
        ["proj.noProject"]     = ("لم يعد المشروع موجوداً.", "The project no longer exists."),
        ["proj.dock.resize"]   = ("اسحب لتغيير عرض اللوحة", "Drag to resize the panel"),

        // ===== مجموعات التبويبات =====
        ["tabgrp.menu"]        = ("المجموعة", "Group"),
        ["tabgrp.new"]         = ("مجموعة جديدة…", "New group…"),
        ["tabgrp.namePrompt"]  = ("اسم المجموعة:", "Group name:"),
        ["tabgrp.defaultName"] = ("مجموعة {0}", "Group {0}"),
        ["tabgrp.rename"]      = ("إعادة تسمية المجموعة…", "Rename group…"),
        ["tabgrp.collapse"]    = ("طيّ المجموعة", "Collapse group"),
        ["tabgrp.expand"]      = ("فرد المجموعة", "Expand group"),
        ["tabgrp.leave"]       = ("إخراج التبويب من المجموعة", "Remove tab from group"),
        ["tabgrp.chipTip"]     = ("انقر لطيّ/فرد المجموعة", "Click to collapse or expand the group"),
        ["tabgrp.close"]       = ("إغلاق المجموعة", "Close group"),
        ["tabgrp.closeConfirm"]= ("سيُغلَق كلّ تبويبات المجموعة «{0}» ({1} تبويباً). لا يمكن التراجع.",
                                  "All {1} tabs in the group “{0}” will be closed. This cannot be undone."),
        ["quick.empty"]        = ("لا أوامر بعد — اضغط «＋ أمر جديد» أو «أضف الأمر الحاليّ».",
                                  "No commands yet — press “＋ New command” or “Add current command”."),
        ["quick.added"]        = ("أُضيف الأمر للمشروع", "Command added to project"),
        ["quick.duplicate"]    = ("أمرٌ مطابق تماماً (نفس الأوامر والاسم والفولدر) موجود مسبقاً — لم يُضَف",
                                  "An identical command (same commands, name and folder) already exists — not added"),
        ["quick.noCurrent"]    = ("لا يوجد أمر حاليّ في التيرمنال النشط", "No current command in the active terminal"),
        ["quick.noTerminal"]   = ("افتح تيرمنالاً أولاً لتشغيل الأمر", "Open a terminal first to run the command"),

        // ===== فتح المسار + محرّر الملفّ داخل التاب (T-7) =====
        ["menu.openFolder"]    = ("فتح المجلّد", "Open folder"),
        ["menu.openFile"]      = ("فتح الملفّ", "Open file"),
        ["editor.save"]        = ("حفظ", "Save"),
        ["editor.dontSave"]    = ("عدم الحفظ", "Don't save"),
        ["editor.cancel"]      = ("إلغاء", "Cancel"),
        ["editor.unsavedTitle"]= ("تغييرات غير محفوظة", "Unsaved changes"),
        ["editor.unsavedMessage"]=("توجد تغييرات غير محفوظة في هذا الملفّ. هل تريد حفظها قبل الإغلاق؟",
                                   "This file has unsaved changes. Do you want to save them before closing?"),

        // ===== مراقب الخوادم (Server Monitor) =====
        ["srv.title"]          = ("مراقب الخوادم", "Server Monitor"),
        ["tip.serverMonitor"]  = ("مراقب الخوادم (تخزين وأداء عبر SSH)", "Server Monitor (storage & performance over SSH)"),
        ["srv.servers"]        = ("الخوادم", "Servers"),
        ["srv.search"]         = ("بحث…", "Search…"),
        ["srv.add"]            = ("إضافة خادم", "Add server"),
        ["srv.edit"]           = ("تعديل", "Edit"),
        ["srv.delete"]         = ("حذف", "Delete"),
        ["srv.duplicate"]      = ("نسخ", "Duplicate"),
        ["srv.connect"]        = ("اتّصال", "Connect"),
        ["srv.disconnect"]     = ("قطع الاتّصال", "Disconnect"),
        ["srv.reconnect"]      = ("إعادة الاتّصال", "Reconnect"),
        ["srv.test"]           = ("اختبار الاتّصال", "Test connection"),
        ["srv.refresh"]        = ("تحديث", "Refresh"),
        ["srv.noServers"]      = ("لا خوادم بعد — أضِف خادماً للبدء", "No servers yet — add one to begin"),
        ["srv.pickServer"]     = ("اختر خادماً واضغط «اتّصال»", "Pick a server and press Connect"),
        ["srv.status.idle"]    = ("غير متّصل", "Disconnected"),
        ["srv.status.connecting"] = ("جارٍ الاتّصال…", "Connecting…"),
        ["srv.status.connected"]  = ("متّصل", "Connected"),
        ["srv.status.failed"]  = ("فشل الاتّصال", "Connection failed"),
        ["srv.status.reconnecting"] = ("انقطع الاتّصال — إعادة الاتّصال…", "Connection lost — reconnecting…"),
        ["srv.lastConnected"]  = ("آخر اتّصال", "Last connected"),
        ["srv.never"]          = ("أبداً", "Never"),
        ["srv.disks"]          = ("الأقراص والمساحة", "Disks & storage"),
        ["srv.col.mount"]      = ("نقطة التركيب", "Mount"),
        ["srv.col.size"]       = ("الحجم", "Size"),
        ["srv.col.used"]       = ("المستخدم", "Used"),
        ["srv.col.avail"]      = ("الفارغ", "Free"),
        ["srv.col.usePct"]     = ("النسبة", "Use%"),
        ["srv.testOk"]         = ("نجح الاتّصال بالخادم.", "Connection succeeded."),
        ["srv.testFail"]       = ("تعذّر الاتّصال بالخادم:", "Could not connect:"),

        // محرّر بروفايل الخادم
        ["srv.ed.addTitle"]    = ("إضافة خادم", "Add server"),
        ["srv.ed.editTitle"]   = ("تعديل الخادم", "Edit server"),
        ["srv.ed.name"]        = ("الاسم", "Name"),
        ["srv.ed.host"]        = ("المضيف (Host/IP)", "Host / IP"),
        ["srv.ed.port"]        = ("المنفذ", "Port"),
        ["srv.ed.user"]        = ("اسم المستخدم", "Username"),
        ["srv.ed.auth"]        = ("المصادقة", "Authentication"),
        ["srv.ed.authPassword"]= ("كلمة مرور", "Password"),
        ["srv.ed.authKey"]     = ("مفتاح خاصّ", "Private key"),
        ["srv.ed.password"]    = ("كلمة المرور", "Password"),
        ["srv.ed.key"]         = ("المفتاح الخاصّ (PEM)", "Private key (PEM)"),
        ["srv.ed.keyPass"]     = ("عبارة مرور المفتاح", "Key passphrase"),
        ["srv.ed.secretKept"]  = ("(محفوظ — اتركه فارغاً للإبقاء عليه)", "(saved — leave blank to keep)"),
        ["srv.ed.color"]       = ("لون مميّز", "Accent color"),
        ["srv.ed.notes"]       = ("ملاحظات", "Notes"),
        ["srv.ed.save"]        = ("حفظ", "Save"),
        ["srv.ed.cancel"]      = ("إلغاء", "Cancel"),
        ["srv.ed.ok"]          = ("حسناً", "OK"),
        ["srv.ed.deleteConfirm"] = ("سيُحذف هذا الخادم نهائيّاً. لا يمكن التراجع عن هذا.", "This server will be permanently deleted. This can’t be undone."),

        // مستكشف المجلّدات (الموجة 2)
        ["srv.tab.dashboard"]  = ("لوحة القيادة", "Dashboard"),
        ["srv.tab.disks"]      = ("الأقراص", "Disks"),
        ["srv.tab.folders"]    = ("المجلّدات", "Folders"),

        // لوحة القيادة
        ["srv.dash.overview"]  = ("نظرة عامّة", "Overview"),
        ["srv.dash.topProc"]   = ("أعلى العمليّات", "Top processes"),
        ["srv.dash.treemap"]   = ("استهلاك المجلّدات (Treemap)", "Folders Usage (Treemap)"),
        ["srv.dash.largest"]   = ("أكبر الملفّات", "Largest Files"),
        ["srv.dash.loadLargest"] = ("عرض أكبر الملفّات", "Load largest files"),
        ["srv.dash.tree"]      = ("الشجرة", "Tree"),
        ["srv.dash.host"]      = ("المضيف", "Host"),
        ["srv.dash.os"]        = ("النظام", "OS"),
        ["srv.dash.kernel"]    = ("النواة", "Kernel"),
        ["srv.dash.cpu"]       = ("المعالج", "CPU"),
        ["srv.dash.ip"]        = ("العنوان", "IP"),
        ["srv.dash.cores"]     = ("نواة", "cores"),
        ["srv.dash.uptime"]    = ("التشغيل", "Uptime"),
        ["srv.dash.load"]      = ("الحِمل (1د)", "Load (1m)"),
        ["srv.dash.ram"]       = ("الذاكرة", "Memory"),
        ["srv.dash.rootDisk"]  = ("القرص /", "Disk /"),
        ["srv.live.toggle"]    = ("● مباشر", "● Live"),
        ["srv.live.updated"]   = ("آخر تحديث:", "Updated:"),
        ["srv.alert.diskFull"] = ("امتلاء قرص", "Disk almost full"),
        ["srv.alert.highLoad"] = ("حِمل عالٍ", "High load"),
        ["srv.folder.scan"]    = ("فحص", "Scan"),
        ["srv.folder.copyPath"]= ("نسخ المسار", "Copy path"),
        ["srv.folder.favorites"] = ("المفضّلة", "Favorites"),
        ["srv.folder.total"]   = ("الإجماليّ", "Total"),
        ["srv.folder.subfolders"] = ("مجلّد فرعيّ", "subfolders"),
        ["srv.folder.empty"]   = ("لا مجلّدات فرعيّة", "No subfolders"),
        ["srv.folder.loading"] = ("جارٍ الفحص…", "Scanning…"),
        ["srv.folder.pathHint"]= ("مسار مطلق (مثل /var)", "Absolute path (e.g. /var)"),
        ["srv.tree.openFiles"] = ("عرض الملفّات هنا", "Show files here"),
        ["srv.tree.openFolders"] = ("فتح في المجلّدات", "Open in Folders"),
        ["srv.tree.refresh"]   = ("تحديث المجلّد", "Refresh folder"),
        ["srv.tree.deleteFolder"] = ("حذف المجلّد", "Delete folder"),
        ["srv.tree.deleteFolderConfirm"] = ("حذف هذا المجلّد وكلّ محتوياته نهائيّاً؟ لا يمكن التراجع.",
                                            "Delete this folder and all its contents permanently? This cannot be undone."),
        ["srv.tree.cantDeleteRoot"] = ("لا يمكن حذف الجذر.", "Cannot delete the root folder."),
        ["srv.tree.upload"]    = ("رفع ملفّات هنا", "Upload files here"),
        ["srv.tree.newFolder"] = ("مجلّد جديد", "New folder"),
        ["srv.tree.folderCreated"] = ("تمّ إنشاء المجلّد", "Folder created"),
        ["srv.up.title"]       = ("رفع", "Upload"),
        ["srv.up.uploading"]   = ("جارٍ الرفع", "Uploading"),
        ["srv.up.cancelled"]   = ("أُلغي الرفع", "Upload cancelled"),
        ["srv.file.deleteManyConfirm"] = ("ستُحذف الملفّات المحدّدة نهائيّاً. لا يمكن التراجع.", "The selected files will be permanently deleted. This can’t be undone."),

        // الملفّات والعمليّات (الموجة 3)
        ["srv.tab.files"]      = ("الملفّات", "Files"),
        ["srv.tab.mgmt"]       = ("الإدارة", "Manage"),
        ["srv.tab.containers"] = ("الحاويات", "Containers"),
        ["srv.containers.title"] = ("حاويات Docker", "Docker containers"),
        ["srv.containers.none"] = ("لا حاويات على هذا الخادم (أو Docker غير مثبّت/بلا صلاحية).", "No containers on this server (or Docker is not installed / no permission)."),
        ["srv.containers.nameTitle"] = ("تسمية الحاوية", "Name container"),
        ["srv.containers.search"] = ("بحث في الحاويات…", "Search containers…"),
        ["srv.containers.enter"] = ("فتح", "Open"),
        ["srv.containers.rename"] = ("تسمية…", "Rename…"),
        ["srv.containers.clearName"] = ("إزالة الاسم", "Clear name"),
        ["srv.containers.noMatch"] = ("لا نتائج مطابقة للبحث.", "No containers match the search."),
        ["srv.ed.sudo"] = ("استخدم sudo لأوامر Docker", "Use sudo for Docker commands"),
        ["srv.ed.sudoHint"] = ("لِلمستخدمين بلا صلاحيّة docker مباشرة. السرد يحتاج sudo بلا كلمة مرور (NOPASSWD)؛ الكونسول يطلب كلمة المرور داخل التبويب عند الحاجة.", "For users without direct docker access. Listing needs passwordless sudo (NOPASSWD); the console prompts for the password inside the tab if required."),
        ["srv.explorer.title"] = ("مستكشف الحاوية", "Container explorer"),
        ["srv.explorer.consoleHere"] = ("الكونسول هنا", "Console here"),
        ["srv.explorer.empty"] = ("مجلّد فارغ", "Empty folder"),
        ["srv.explorer.copy"] = ("نسخ", "Copy"),
        ["srv.explorer.open"] = ("فتح", "Open"),
        ["srv.explorer.download"] = ("تنزيل…", "Download…"),
        ["srv.explorer.console"] = ("الكونسول", "Console"),
        ["srv.explorer.redock"] = ("إرجاع للواجهة", "Dock back"),
        ["srv.explorer.rename"] = ("إعادة تسمية", "Rename"),
        ["srv.explorer.delete"] = ("حذف", "Delete"),
        ["srv.explorer.delConfirm"] = ("سيُحذف هذا الملفّ نهائيّاً. لا يمكن التراجع.", "This file will be permanently deleted. This can’t be undone."),
        ["srv.explorer.delDirConfirm"] = ("سيُحذف هذا المجلّد بمحتوياته نهائيّاً. لا يمكن التراجع.", "This folder and its contents will be permanently deleted. This can’t be undone."),
        ["srv.explorer.newFolder"] = ("مجلّد جديد", "New folder"),
        ["srv.explorer.namePlaceholder"] = ("الاسم", "Name"),
        ["srv.explorer.upload"] = ("رفع ملفّ", "Upload file"),
        ["srv.explorer.edit"] = ("تعديل", "Edit"),
        ["srv.explorer.save"] = ("حفظ", "Save"),
        ["srv.explorer.saved"] = ("تمّ الحفظ.", "Saved."),
        ["srv.explorer.customShell"] = ("أمر مخصّص", "Custom command"),
        ["srv.explorer.view.binary"] = ("ملفّ ثنائيّ — لا يمكن عرضه كنصّ.", "Binary file — cannot be shown as text."),
        ["srv.explorer.view.truncated"] = ("عُرِض أوّل 512KB فقط (الملفّ أكبر).", "Showing first 512KB only (file is larger)."),

        // ترويسات أعمدة قائمة الملفّات (قابلة للنقر للفرز)
        ["srv.explorer.colName"]     = ("الاسم", "Name"),
        ["srv.explorer.colType"]     = ("النوع", "Type"),
        ["srv.explorer.colSize"]     = ("الحجم", "Size"),
        ["srv.explorer.colModified"] = ("عُدِّل", "Modified"),

        // أنواع المداخل في مستكشف الحاوية (نصّ مترجَم بدل الامتداد الخام)
        ["srv.type.folder"]  = ("مجلّد", "Folder"),
        ["srv.type.link"]    = ("رابط", "Link"),
        ["srv.type.file"]    = ("ملفّ", "File"),
        ["srv.type.text"]    = ("نصّ", "Text"),
        ["srv.type.data"]    = ("بيانات", "Data"),
        ["srv.type.code"]    = ("شفرة", "Code"),
        ["srv.type.image"]   = ("صورة", "Image"),
        ["srv.type.archive"] = ("أرشيف", "Archive"),
        ["srv.type.video"]   = ("فيديو", "Video"),
        ["srv.type.audio"]   = ("صوت", "Audio"),
        ["srv.type.web"]     = ("صفحة ويب", "Web page"),
        ["srv.type.binary"]  = ("ثنائيّ", "Binary"),
        ["srv.type.doc"]     = ("مستند", "Document"),

        // أزرار الحوارات + حوارات الحذف في النافذة الرئيسيّة (تُراعي اللغة)
        ["dlg.cancel"] = ("إلغاء", "Cancel"),
        ["dlg.delete"] = ("حذف", "Delete"),
        ["dlg.save"]   = ("حفظ", "Save"),
        ["ctx.open"]   = ("فتح", "Open"),
        ["ctx.edit"]   = ("تعديل", "Edit"),
        ["ctx.download"] = ("تنزيل…", "Download…"),
        ["ctx.rename"] = ("إعادة تسمية…", "Rename…"),
        ["ctx.consoleHere"] = ("الكونسول هنا", "Console here"),
        ["ctx.close"]  = ("إغلاق", "Close"),
        ["ctx.cut"]        = ("قصّ", "Cut"),
        ["ctx.copy"]       = ("نسخ", "Copy"),
        ["ctx.paste"]      = ("لصق", "Paste"),
        ["ctx.selectAll"]  = ("تحديد الكلّ", "Select All"),
        ["ctx.clear"]      = ("مسح الصندوق", "Clear box"),

        // ===== قاموس الأوامر =====
        ["dict.title"]      = ("قاموس الأوامر", "Command dictionary"),
        ["dict.subtitle"]   = ("مكتبتك من الأوامر. ابحث بأيّ حروف تذكرها — أوائل الكلمات تكفي — ثمّ أدرِج المختار في التيرمنال لتراجعه قبل تنفيذه.",
                               "Your command library. Search by any letters you remember — word initials are enough — then insert the pick into the terminal to review before running."),
        ["dict.searchHint"] = ("ابحث… (مثال: dpa ⟵ docker ps -a)", "Search… (e.g. dpa → docker ps -a)"),
        ["dict.f.title"]       = ("العنوان", "Title"),
        ["dict.f.command"]     = ("الأمر", "Command"),
        ["dict.f.description"] = ("الشرح", "Description"),
        ["dict.f.tags"]        = ("الوسوم (تفصلها مسافة)", "Tags (space separated)"),
        ["dict.new"]        = ("جديد", "New"),
        ["dict.import"]     = ("استيراد…", "Import…"),
        ["dict.export"]     = ("تصدير…", "Export…"),
        ["dict.delete"]     = ("حذف", "Delete"),
        ["dict.insert"]     = ("إدراج في التيرمنال", "Insert into terminal"),
        ["dict.close"]      = ("إغلاق", "Close"),
        ["dict.newTitle"]   = ("أمر جديد", "New command"),
        ["dict.used"]       = ("استُعمل {0} مرّة", "Used {0} time(s)"),
        ["dict.emptyStore"] = ("القاموس فارغ. أضف أمراً بزرّ «جديد»، أو أشِّر أمراً في صندوق التيرمنال وأضفه من قائمته.",
                               "The dictionary is empty. Add one with “New”, or select a command in the terminal box and add it from its menu."),
        ["dict.emptySearch"]= ("لا نتائج لهذا البحث.", "No matches for this search."),
        ["dict.deleteConfirm"] = ("سيُحذف «{0}» من القاموس نهائيّاً.", "“{0}” will be permanently removed from the dictionary."),
        ["dict.exported"]   = ("صُدِّر {0} أمراً إلى:\n{1}", "Exported {0} command(s) to:\n{1}"),
        ["dict.imported"]   = ("أُضيف {0} · حُدِّث {1} · تُخطّي {2}", "Added {0} · updated {1} · skipped {2}"),
        ["dict.addFrom"]    = ("أضف إلى قاموس الأوامر", "Add to command dictionary"),
        ["dict.added"]      = ("أُضيف إلى القاموس", "Added to the dictionary"),
        ["keys.dictionary"] = ("قاموس الأوامر", "Command dictionary"),

        // ===== نوم التبويب =====
        ["tabctx.sleep"]       = ("أنِم التبويب", "Put tab to sleep"),
        ["tabctx.wake"]        = ("أيقِظ التبويب", "Wake tab"),
        ["tabctx.sleepAll"]    = ("أنِم كلّ التبويبات", "Put all tabs to sleep"),
        ["tabctx.sleepAfter"]  = ("أنِم ما بعده", "Put tabs after this to sleep"),
        ["sleep.title"]        = ("التبويب نائم", "Tab is asleep"),
        ["sleep.hint"]         = ("لم تبدأ الصدفة في هذا التبويب. يبقى نائماً حتّى تُشغّله بنفسك، ثمّ يعمل بعدها عاديّاً.",
                                  "The shell has not started in this tab. It stays asleep until you start it yourself, then behaves normally."),
        ["sleep.run"]          = ("تشغيل", "Start"),
        ["sleep.confirmTitle"] = ("إنامة تبويبٍ يعمل؟", "Sleep a running tab?"),
        ["sleep.confirmMsg"]   = ("«{0}» ينفّذ أمراً الآن. الإنامة تُنهي الصدفة وما يعمل فيها.",
                                  "“{0}” is running a command. Sleeping ends the shell and whatever runs in it."),
        ["sleep.confirmMany"]  = ("{0} من التبويبات تنفّذ أوامر الآن. الإنامة تُنهي صدفاتها وما يعمل فيها.",
                                  "{0} tab(s) are running commands. Sleeping ends their shells and whatever runs in them."),
        ["dlg.proj.title"]   = ("حذف المشروع؟", "Delete project?"),
        ["dlg.proj.msg"]     = ("سيُحذف المشروع «{0}» نهائيّاً. لا يمكن التراجع عن هذا.", "“{0}” will be permanently deleted. This can’t be undone."),
        ["dlg.proj.msgN"]    = ("سيُحذف المشروع «{0}» و{1} من أوامره نهائيّاً. لا يمكن التراجع عن هذا.", "“{0}” and its {1} command(s) will be permanently deleted. This can’t be undone."),
        ["dlg.tag.title"]    = ("حذف التاك؟", "Delete tag?"),
        ["dlg.tag.msg"]      = ("سيُحذف التاك «{0}» نهائيّاً. لا يمكن التراجع.", "“{0}” will be permanently deleted. This can’t be undone."),
        ["dlg.tag.msgN"]     = ("سيُحذف التاك «{0}» ويُفكّ من {1} مشروعاً (لا تُحذَف المشاريع). لا يمكن التراجع.", "“{0}” will be deleted and detached from {1} project(s) (projects are kept). This can’t be undone."),
        ["dlg.profile.title"]     = ("حذف البروفايل؟", "Delete profile?"),
        ["dlg.profile.msg"]       = ("سيُحذف البروفايل «{0}» نهائيّاً. لا يمكن التراجع.", "“{0}” will be permanently deleted. This can’t be undone."),
        ["dlg.profile.pickTitle"] = ("بروفايلات الصدفات", "Shell profiles"),
        ["dlg.profile.pickMsg"]   = ("اختر بروفايلاً مخصّصاً لحذفه.", "Select a custom profile to delete."),

        // الإدارة (عمليّات + خدمات + منافذ)
        ["srv.mgmt.memory"]    = ("🧠 الذاكرة", "🧠 Memory"),
        ["srv.mgmt.cpu"]       = ("⚙ الحِمل / الأنوية", "⚙ Load / cores"),
        ["srv.mgmt.swap"]      = ("💾 التبديل (Swap)", "💾 Swap"),
        ["srv.mgmt.topMem"]    = ("أعلى مستهلكي الذاكرة", "Top memory consumers"),
        ["srv.mgmt.topCpu"]    = ("أعلى مستهلكي المعالج", "Top CPU consumers"),
        ["srv.mgmt.memApps"]   = ("تطبيقات", "Apps"),
        ["srv.mgmt.memCache"]  = ("كاش/مؤقّت", "Cache"),
        ["srv.mgmt.memFree"]   = ("حرّ", "Free"),
        ["srv.mgmt.memAvail"]  = ("متاح", "Available"),
        ["ctx.options"]        = ("خيارات", "Options"),

        // ===== قائمة التبويب (النافذة) وقائمة المشروع =====
        ["tabctx.rename"]      = ("إعادة تسمية التبويب…", "Rename tab…"),
        ["tabctx.duplicate"]   = ("تكرار التبويب", "Duplicate tab"),
        ["tabctx.detach"]      = ("فصل إلى نافذة مستقلّة", "Detach to new window"),
        ["tabctx.openExplorer"] = ("فتح في المستكشف", "Open in Explorer"),
        ["explorer.notfound"]  = ("مجلّد العمل غير موجود.", "Working directory not found."),
        ["tabctx.copyTitle"]   = ("نسخ عنوان التبويب", "Copy tab title"),
        ["tabctx.copyCwd"]     = ("نسخ مجلّد العمل", "Copy working directory"),
        ["tabctx.moveStart"]   = ("نقل للأمام", "Move tab forward"),
        ["tabctx.moveEnd"]     = ("نقل للخلف", "Move tab back"),
        ["tabctx.close"]       = ("إغلاق التبويب", "Close tab"),
        ["tabctx.closeOthers"] = ("إغلاق التبويبات الأخرى", "Close other tabs"),
        ["tabctx.closeAfter"]  = ("إغلاق ما بعده", "Close tabs after this"),
        ["tabctx.rename.msg"]  = ("اسم التبويب الجديد:", "New tab name:"),
        ["tabctx.color.none"]  = ("بلا لون", "No color"),

        ["projctx.openNew"]    = ("فتح في تبويب جديد", "Open in new tab"),
        ["projctx.copyName"]   = ("نسخ اسم المشروع", "Copy project name"),
        ["projctx.copyPath"]   = ("نسخ الباث", "Copy path"),
        ["projctx.explorer"]   = ("فتح في المستكشف", "Reveal in File Explorer"),
        ["projctx.duplicate"]  = ("تكرار المشروع", "Duplicate project"),
        ["projctx.rename"]     = ("إعادة تسمية…", "Rename…"),
        ["projctx.rename.msg"] = ("اسم المشروع الجديد:", "New project name:"),
        ["projctx.color"]      = ("لون المشروع", "Project color"),
        ["projctx.copy.suffix"]= ("نسخة", "copy"),

        // تقرير الأخطاء غير المتوقّعة (CrashReporter)
        ["crash.title"]    = ("حدث خطأ غير متوقّع", "Unexpected error"),
        ["crash.message"]  = ("حصل خطأ غير متوقّع وحُفِظت تفاصيله في ملفّ سجلّ.\nيمكنك متابعة العمل، لكن يُستحسن إعادة تشغيل التطبيق إن تكرّر.",
                              "An unexpected error occurred and the details were saved to a log file.\nYou can keep working, but restarting is advised if it repeats."),
        ["crash.fatal"]    = ("حدث خطأ أوقف التطبيق. حُفِظت التفاصيل في ملفّ السجلّ.",
                              "An error stopped the app. The details were saved to the log file."),
        ["crash.openLog"]  = ("فتح ملفّ السجلّ", "Open log file"),
        ["crash.continue"] = ("متابعة", "Continue"),

        // إشعار انتهاء أمر طويل (يظهر حين تكون النافذة غير نشطة)
        ["notify.cmdDone"]   = ("انتهى الأمر", "Command finished"),
        ["notify.cmdFailed"] = ("فشل الأمر", "Command failed"),

        // التحديث من إصدارات GitHub (Velopack): فحص صامت ← إشعار ← موافقة ← تنزيل ← إعادة تشغيل
        ["update.available"]    = ("تحديث متوفّر", "Update available"),
        ["update.availableMsg"] = ("النسخة {0} جاهزة للتنزيل (الحاليّة {1}). اضغط هنا للتحديث.",
                                   "Version {0} is ready to download (you have {1}). Click here to update."),
        ["update.confirmTitle"] = ("تحديث إلى النسخة {0}؟", "Update to version {0}?"),
        ["update.confirmMsg"]   = ("سيُنزَّل التحديث في الخلفيّة، ثمّ نسألك عن إعادة التشغيل.",
                                   "The update will download in the background, then we'll ask about restarting."),
        ["update.now"]          = ("تحديث الآن", "Update now"),
        ["update.later"]        = ("لاحقاً", "Later"),
        ["update.downloading"]  = ("تنزيل التحديث", "Downloading update"),
        ["update.restartTitle"] = ("النسخة {0} جاهزة", "Version {0} is ready"),
        ["update.restartMsg"]   = ("أُنزِّل التحديث. إعادة التشغيل الآن تفتح النسخة الجديدة مباشرةً؛ وإلّا يُطبَّق عند إغلاق التطبيق.",
                                   "The update was downloaded. Restarting now opens the new version immediately; otherwise it is applied when you close the app."),
        ["update.restartNow"]   = ("أعد التشغيل الآن", "Restart now"),
        ["update.ready"]    = ("تحديث جاهز", "Update ready"),
        ["update.readyMsg"] = ("نُزِّلت النسخة {0} — تُطبَّق تلقائيّاً عند إعادة تشغيل التطبيق.",
                               "Version {0} was downloaded — it will be applied when you restart the app."),
        ["update.upToDate"]     = ("أنت على أحدث نسخة", "You're up to date"),
        ["update.upToDateMsg"]  = ("النسخة {0} هي الأحدث.", "Version {0} is the latest."),
        ["update.checking"]     = ("جارٍ الفحص…", "Checking…"),
        ["update.failed"]       = ("تعذّر التحديث", "Update failed"),
        ["update.failedMsg"]    = ("تعذّر الوصول إلى إصدارات GitHub. تحقّق من الاتّصال وأعد المحاولة.",
                                   "Couldn't reach GitHub releases. Check your connection and try again."),
        ["update.check"]        = ("تحقّق من التحديثات", "Check for updates"),
        ["tip.update"]          = ("تحديث متوفّر", "Update available"),
        ["srv.mgmt.swapLabel"] = ("التبديل (Swap)", "Swap"),
        ["srv.mgmt.processes"] = ("العمليّات", "Processes"),
        ["srv.mgmt.services"]  = ("الخدمات", "Services"),
        ["srv.mgmt.ports"]     = ("المنافذ المُنصِتة", "Listening ports"),
        ["srv.mgmt.kill"]      = ("إنهاء العمليّة", "Kill process"),
        ["srv.mgmt.kill9"]     = ("إنهاء إجباريّ (-9)", "Force kill (-9)"),
        ["srv.mgmt.killConfirm"] = ("إنهاء العمليّة رقم", "Kill process"),
        ["srv.mgmt.killed"]    = ("تمّ إنهاء العمليّة", "Process killed"),
        ["srv.mgmt.start"]     = ("تشغيل", "Start"),
        ["srv.mgmt.stop"]      = ("إيقاف", "Stop"),
        ["srv.mgmt.restart"]   = ("إعادة تشغيل", "Restart"),
        ["srv.files.scan"]     = ("أكبر الملفّات", "Largest files"),
        ["srv.files.search"]   = ("بحث في النتائج…", "Search results…"),
        ["srv.files.filesWord"]= ("ملفّ", "files"),
        ["srv.files.export"]   = ("تصدير CSV", "Export CSV"),
        ["srv.col.name"]       = ("الاسم", "Name"),
        ["srv.col.ext"]        = ("الامتداد", "Extension"),
        ["srv.col.modified"]   = ("التعديل", "Modified"),
        ["srv.col.path"]       = ("المسار", "Path"),
        ["srv.file.download"]  = ("تنزيل", "Download"),
        ["srv.file.viewLog"]   = ("عرض (آخر 1000 سطر)", "View (last 1000 lines)"),
        ["srv.file.rename"]    = ("إعادة تسمية", "Rename"),
        ["srv.file.copyPath"]  = ("نسخ المسار", "Copy path"),
        ["srv.file.whichContainer"] = ("اعرف الحاوية", "Which container?"),
        ["srv.docker.resolving"] = ("جارٍ تحديد الحاوية…", "Identifying container…"),
        ["srv.docker.notDocker"] = ("هذا الملفّ ليس داخل طبقة overlay2 ولا حجم Docker.", "This file is not inside a Docker overlay2 layer or volume."),
        ["srv.docker.overlayLayer"] = ("طبقة overlay2", "overlay2 layer"),
        ["srv.docker.volume"]  = ("حجم Docker", "Docker volume"),
        ["srv.docker.noOwner"] = ("لم يُعثر على حاوية تملك طبقة الكتابة هذه (قد تكون طبقة صورة أساس مشتركة، أو Docker غير متوفّر/بلا صلاحية).", "No container owns this writable layer (it may be a shared base-image layer, or Docker is unavailable)."),
        ["srv.docker.noVolOwner"] = ("لا حاوية تُركّب هذا الحجم حاليّاً.", "No container currently mounts this volume."),
        ["srv.docker.image"]   = ("الصورة", "Image"),
        ["srv.docker.status"]  = ("الحالة", "Status"),
        ["srv.docker.rwLayer"] = ("الملفّ في طبقة الكتابة لهذه الحاوية (المالك الحصريّ).", "File is in this container's writable layer (exclusive owner)."),
        ["srv.docker.mounted"] = ("حجم مُركَّب في هذه الحاوية.", "Volume mounted in this container."),
        ["srv.docker.ownerTitle"] = ("الحاوية المالكة", "Owning container"),
        ["srv.docker.copyName"] = ("نسخ الاسم", "Copy name"),
        ["srv.docker.copyId"]  = ("نسخ المعرّف", "Copy ID"),
        ["srv.docker.enter"]   = ("فتح الحاوية", "Open container"),
        ["srv.docker.sshMissing"] = ("عميل OpenSSH (ssh.exe) غير متوفّر على هذا الجهاز. فعّل «OpenSSH Client» من إعدادات ويندوز (الميزات الاختياريّة) ثمّ أعد المحاولة.", "The OpenSSH client (ssh.exe) is not available on this machine. Enable 'OpenSSH Client' from Windows optional features and try again."),
        ["srv.file.delete"]    = ("حذف", "Delete"),
        ["srv.file.deleteTitle"] = ("حذف الملفّ", "Delete file"),
        ["srv.file.deleteConfirm"] = ("سيُحذف هذا الملفّ نهائيّاً. لا يمكن التراجع.", "This file will be permanently deleted. This can’t be undone."),
        ["srv.file.downloadOk"]= ("تمّ التنزيل بنجاح.", "Download complete."),
        ["srv.file.downloadFail"] = ("تعذّر التنزيل:", "Download failed:"),
        ["srv.file.opFail"]    = ("فشلت العمليّة:", "Operation failed:"),
        ["srv.file.loading"]   = ("جارٍ الفحص…", "Scanning…"),
        ["srv.log.search"]     = ("بحث في السجلّ (Enter)…", "Search log (Enter)…"),
        ["srv.toast.copied"]   = ("تمّ نسخ المسار", "Path copied"),
        ["srv.folder.filesIn"] = ("ملفّات:", "Files in:"),
        ["srv.folder.noFiles"] = ("لا ملفّات مباشرة في هذا المجلّد", "No files directly in this folder"),
        ["srv.folder.detailHint"] = ("اضغط مجلّداً لعرض ملفّاته", "Click a folder to view its files"),
        ["srv.font.smaller"]   = ("تصغير خطّ التفاصيل", "Smaller detail font"),
        ["srv.font.larger"]    = ("تكبير خطّ التفاصيل", "Larger detail font"),
        ["srv.font.tip"]       = ("حجم خطّ التفاصيل", "Detail font size"),
        ["srv.dl.downloading"] = ("تنزيل", "Downloading"),
        ["srv.dl.cancelled"]   = ("أُلغي التنزيل", "Download cancelled"),
        ["srv.file.deleted"]   = ("تمّ الحذف", "Deleted"),
        ["srv.file.renamed"]   = ("تمّت إعادة التسمية", "Renamed"),
        ["srv.files.empty"]    = ("لا ملفّات", "No files"),
        ["srv.files.noMatch"]  = ("لا نتائج للبحث", "No matches"),

        // قائمة أدوات النظام (زرّ الأدوات في الواجهة الرئيسة)
        ["tools.menu"]         = ("أدوات النظام", "System tools"),
        ["tools.serverMonitor"]= ("مراقب الخوادم", "Server Monitor"),

        // ===== مساعد الـ AI: لوحة الدردشة =====
        ["ai.panel.title"]     = ("مساعد الذكاء الاصطناعي", "AI assistant"),
        ["ai.panel.ask"]       = ("اسأل عن أيّ شيء…", "Ask anything…"),
        ["ai.panel.send"]      = ("إرسال", "Send"),
        ["ai.panel.stop"]      = ("إيقاف", "Stop"),
        ["ai.panel.clear"]     = ("محادثة جديدة", "New conversation"),

        // ===== الأسماء المستعارة (اختصارات نصّيّة تتوسّع إلى أوامر) =====
        ["alias.nav"]          = ("الأوامر المختصرة", "Aliases"),
        ["alias.title"]        = ("الأوامر المختصرة", "Command aliases"),
        ["alias.hint"]         = ("كلمة تكتبها في صندوق الأوامر فتتوسّع إلى عدّة أوامر. المتغيّرات تأخذ قيمها من الوسائط بترتيب تعريفها: gpc \"رسالة\" يملأ أوّل متغيّر.",
                                  "A word you type in the command box that expands into several commands. Variables take their values from the arguments in declaration order: gpc \"message\" fills the first variable."),
        ["alias.shell"]        = ("سجّلها في الصدفة نفسها (تعمل داخل التيرمنال مباشرةً)",
                                  "Register them in the shell itself (they work inside the terminal directly)"),
        ["alias.shellHint"]    = ("بدونها تعمل الأسماء المختصرة في صندوق الإدخال وأوامر المشاريع فقط. مع تفعيلها تُسجَّل في كلّ تيرمنال جديد (doskey لـcmd · دالّة لـPowerShell · دالّة لـbash) فتعمل حتّى لو كتبتها داخل الشاشة السوداء. لا يُعدَّل أيّ ملفّ تهيئة يخصّك. الاسم الذي يطلب تأكيداً قبل التنفيذ لا يُسجَّل — الصدفة لا تعرف حوار التأكيد. ولا تشمل WSL ولا البروفايلات المخصّصة.",
                                  "Without it, aliases work only in the input box and project commands. With it, they are registered in every new terminal (doskey for cmd · a function for PowerShell · a function for bash) so they work even when typed inside the black screen. None of your own config files are modified. An alias that asks for confirmation is not registered — the shell knows no confirmation dialog. WSL and custom profiles are not covered."),
        ["alias.shellFolder"]  = ("ملفّات التسجيل المولَّدة", "Generated registration files"),
        ["alias.add"]          = ("اسم مستعار جديد", "New alias"),
        ["alias.edit"]         = ("تحرير", "Edit"),
        ["alias.delete"]       = ("حذف", "Delete"),
        ["alias.run"]          = ("نفّذ", "Run"),
        ["alias.empty"]        = ("لا أسماء مستعارة بعد. أنشئ واحداً واكتب كلمته في صندوق الأوامر لتتوسّع إلى أوامرك.",
                                  "No aliases yet. Create one, then type its word in the command box to expand it into your commands."),
        ["alias.name"]         = ("الكلمة", "Word"),
        ["alias.nameHint"]     = ("بلا مسافات — مثل gpc", "No spaces — e.g. gpc"),
        ["alias.desc"]         = ("الوصف", "Description"),
        ["alias.namePh"]       = ("gpc", "gpc"),
        ["alias.descPh"]       = ("أضف الكلّ واعمل كوميت وادفع", "stage everything, commit and push"),
        ["alias.vars"]         = ("المتغيّرات", "Variables"),
        ["alias.varsHint"]     = ("قيمة تكتبها بعد الكلمة عند الاستدعاء فتُستبدَل داخل الأوامر. تُملأ بترتيب تعريفها هنا: أوّل متغيّر يأخذ أوّل قيمة.",
                                  "A value you type after the word when calling the alias; it is substituted inside the commands. Values fill in the order declared here: the first variable takes the first value."),
        ["alias.varsEmpty"]    = ("لا متغيّرات — الأوامر تُنفَّذ كما هي. أضف متغيّراً إن أردت تمرير قيمة عند الاستدعاء.",
                                  "No variables — the commands run as written. Add one if you want to pass a value when calling the alias."),
        ["alias.varAdd"]       = ("أضف متغيّراً", "Add variable"),
        ["alias.varHead"]      = ("المتغيّر {0}", "Variable {0}"),
        ["alias.varRemove"]    = ("احذف هذا المتغيّر", "Remove this variable"),
        ["alias.varName"]      = ("الاسم", "Name"),
        ["alias.varNamePh"]    = ("msg", "msg"),
        ["alias.varNameTip"]   = ("حروف وأرقام وشرطة سفليّة فقط. هذا ما تكتبه في الأوامر مسبوقاً بـ$.",
                                  "Letters, digits and underscore only. This is what you write in the commands, prefixed with $."),
        ["alias.varLabel"]     = ("الوصف", "Description"),
        ["alias.varLabelPh"]   = ("رسالة الكوميت", "the commit message"),
        ["alias.varLabelTip"]  = ("يُذكّرك بما يعنيه المتغيّر، ويظهر في رسالة الخطأ حين ينقص.",
                                  "Reminds you what the variable means, and appears in the error message when it is missing."),
        ["alias.varDefault"]   = ("قيمة افتراضيّة", "Default value"),
        ["alias.varDefaultPh"] = ("تحديث", "update"),
        ["alias.varDefaultTip"]= ("تُستعمَل حين لا تمرّر قيمة عند الاستدعاء. اتركها فارغة إن لا افتراضيّ.",
                                  "Used when you pass no value at call time. Leave empty for no default."),
        ["alias.varRequired"]  = ("إلزاميّ — أوقف التنفيذ إن لم تُعطَ قيمة",
                                  "Required — stop the run when no value is given"),
        ["alias.varUse"]       = ("اكتبه في الأوامر هكذا: {0}", "Write it in the commands as: {0}"),
        ["alias.varUseEmpty"]  = ("سمِّ المتغيّر لترى كيف تكتبه في الأوامر.",
                                  "Name the variable to see how to write it in the commands."),
        ["alias.commands"]     = ("الأوامر (سطر لكلّ أمر)", "Commands (one per line)"),
        ["alias.commandsPh"]   = ("git add .\ngit commit -m \"$msg\"\ngit push", "git add .\ngit commit -m \"$msg\"\ngit push"),
        ["alias.commandsHint"] = ("استعمل $اسم_المتغيّر داخل الأمر. و$1..$9 للوسائط بموضعها، و$@ لكلّها.",
                                  "Use $variableName inside a command. Also $1..$9 for positional arguments, and $@ for all of them."),
        ["alias.shell"]        = ("الصدفة المستهدفة (فارغ = الكلّ)", "Target shell (empty = all)"),
        ["alias.shellPh"]      = ("pwsh", "pwsh"),
        ["alias.confirm"]      = ("اعرض الأوامر واطلب تأكيداً قبل التنفيذ", "Show the commands and confirm before running"),
        ["alias.enabled"]      = ("مفعَّل", "Enabled"),
        ["alias.save"]         = ("حفظ", "Save"),
        ["alias.errName"]      = ("الكلمة مطلوبة وبلا مسافات.", "The word is required and must contain no spaces."),
        ["alias.errCommands"]  = ("أضف أمراً واحداً على الأقلّ.", "Add at least one command."),
        ["alias.errMissing"]   = ("ينقص المتغيّر «{0}» — مرّره كوسيط أو أعطه قيمة افتراضيّة.",
                                  "Missing variable \"{0}\" — pass it as an argument or give it a default."),
        ["alias.errEmpty"]     = ("لا أوامر في هذا الاسم المستعار.", "This alias has no commands."),
        ["alias.deleteConfirm"]=("سيُحذف الاسم المستعار «{0}». لا يمكن التراجع.",
                                  "The alias \"{0}\" will be deleted. This cannot be undone."),

        // ===== نصوص كانت مكتوبة عربيّةً في XAML فلا تتبع اللغة =====
        // ‏XAML يقرؤها الآن عبر {loc:T} مباشرةً: لا اسم عنصر ولا سطر في الكود يُنسى.
        ["ui.addCmd"]          = ("إضافة أمر", "Add command"),
        ["ui.collapsePanel"]   = ("طيّ اللوحة", "Collapse the panel"),
        ["ui.projectFolder"]   = ("فولدر المشروع", "Project folder"),
        ["ui.addTag"]          = ("＋ تاك", "＋ Tag"),
        ["ui.browse"]          = ("استعراض", "Browse"),
        ["ui.apply"]           = ("تطبيق", "Apply"),
        ["ui.cancel"]          = ("إلغاء", "Cancel"),
        ["ui.save"]            = ("حفظ", "Save"),
        ["ui.customColor"]     = ("لون مخصّص (#RRGGBB)", "Custom colour (#RRGGBB)"),
        ["ui.composerRich"]    = ("صندوق إدخال غنيّ منفصل (نمط Warp)", "Separate rich input box (Warp style)"),
        ["ui.composerRichHint"]= ("صندوق أمر واضح أسفل التيرمنال مع اقتراحات وإكمال شبحيّ. إطفاؤه يعيد الكتابة داخل الشبكة مباشرةً. يختفي تلقائياً في محرّرات كامل الشاشة.",
                                  "A clear command box under the terminal with suggestions and ghost completion. Turning it off returns typing to the grid itself. It hides automatically in full-screen editors."),
        ["ui.interactive"]     = ("برامج تُخفي صندوق الإدخال", "Programs that hide the input box"),
        ["ui.interactiveHint"] = ("صندوق الإدخال يبقى ظاهراً أثناء تنفيذ الأوامر العاديّة (فيمكن إيقافها بـCtrl+C)، ويختفي فقط لهذه البرامج — لأنّها تقرأ كلّ ضغطة مفتاح وتحتاج الشاشة كاملة. أسماء مفصولة بفواصل أو أسطر. اتركه فارغاً للقائمة الافتراضيّة.",
                                  "The input box stays visible while ordinary commands run (so Ctrl+C can stop them), and hides only for these programs — they read every keystroke and need the full screen. Names separated by commas or new lines. Leave empty for the default list."),

        // بروفايلات الصدفات
        ["prof.title"]         = ("بروفايلات الصدفات", "Shell profiles"),
        ["prof.default"]       = ("البروفايل الافتراضيّ", "Default profile"),
        ["prof.add"]           = ("إضافة", "Add"),
        ["prof.edit"]          = ("تعديل", "Edit"),
        ["prof.delete"]        = ("حذف", "Delete"),
        ["prof.close"]         = ("إغلاق", "Close"),
        ["prof.name"]          = ("الاسم", "Name"),
        ["prof.exe"]           = ("الملفّ التنفيذيّ (ExePath)", "Executable (ExePath)"),
        ["prof.args"]          = ("الوسائط (Arguments)", "Arguments"),
        ["prof.cwd"]           = ("مجلّد العمل", "Working directory"),
        ["prof.env"]           = ("متغيّرات البيئة (KEY=VALUE في كل سطر)", "Environment variables (KEY=VALUE per line)"),

        // شريط التيرمنال والبحث في المخرجات
        ["term.restart"]       = ("إعادة التشغيل", "Restart"),
        ["term.stop"]          = ("إيقاف", "Stop"),
        ["term.clear"]         = ("تنظيف الشاشة", "Clear the screen"),
        ["term.closePane"]     = ("إغلاق هذا الجزء (Ctrl+W)", "Close this pane (Ctrl+W)"),
        ["find.prev"]          = ("السابق (Shift+Enter)", "Previous (Shift+Enter)"),
        ["find.next"]          = ("التالي (Enter)", "Next (Enter)"),
        ["find.close"]         = ("إغلاق (Esc)", "Close (Esc)"),

        // مراقب الخوادم ومستكشف الحاوية
        ["srv.detailFont"]     = ("حجم خطّ التفاصيل", "Detail font size"),
        ["srv.diskDblClick"]   = ("نقر مزدوج: دخول القرص وتصفّح مجلّداته", "Double-click: enter the disk and browse its folders"),
        ["srv.showFolders"]    = ("عرض المجلّدات", "Show folders"),
        ["exp.root"]           = ("الجذر (/)", "Root (/)"),
        ["exp.up"]             = ("أعلى", "Up"),
        ["exp.newFolder"]      = ("مجلّد جديد هنا", "New folder here"),
        ["exp.upload"]         = ("رفع ملفّ هنا", "Upload a file here"),
        ["exp.newTerminal"]    = ("تيرمنال جديد", "New terminal"),

        // ===== فتح التطبيق من مستكشف ويندوز بكلمة قصيرة =====
        ["launch.title"]       = ("فتحه من ويندوز", "Launch from Windows"),
        ["launch.hint"]        = ("سجّل كلمة قصيرة تكتبها في شريط عنوان المستكشف أو في «تشغيل» (Win+R) — كما تكتب cmd — فيُفتح التطبيق في المجلد الذي أنت فيه.",
                                  "Register a short word you can type in Explorer's address bar or the Run box (Win+R) — the way you type cmd — and the app opens in the folder you are in."),
        ["launch.keyword"]     = ("الكلمة", "Keyword"),
        ["launch.enable"]      = ("سجّل الكلمة", "Register"),
        ["launch.disable"]     = ("أزل التسجيل", "Unregister"),
        ["launch.on"]          = ("مسجَّلة ✓ — اكتب «{0}» في شريط عنوان أيّ مجلد.",
                                  "Registered ✓ — type “{0}” in any folder's address bar."),
        ["launch.off"]         = ("غير مسجَّلة.", "Not registered."),
        ["launch.errKeyword"]  = ("الكلمة تقبل الحروف والأرقام والشرطة فقط، وبطول 24 محرفاً على الأكثر.",
                                  "The keyword accepts letters, digits and dashes only, up to 24 characters."),
        ["launch.errExe"]      = ("تعذّر تحديد ملفّ التطبيق التنفيذيّ.", "Could not determine the application's executable."),
        ["launch.errFail"]     = ("تعذّر التسجيل: {0}", "Registration failed: {0}"),
        ["launch.note"]        = ("يُكتب التسجيل لحسابك وحدك بلا صلاحيّة مسؤول. وإن نقلتَ ملفّات التطبيق فأعد التسجيل.",
                                  "The registration is written for your account only, with no administrator rights. Re-register if you move the application files."),

        // ===== الدليل (صفحات HTML تُفتح في المتصفّح) =====
        ["docs.open"]          = ("الدليل", "Guide"),
        ["docs.tip"]           = ("افتح شرح هذا القسم في الدليل", "Open the guide for this section"),
        ["docs.tipMain"]       = ("دليل الاستعمال — شرح كلّ شيء في التطبيق",
                                  "User guide — everything in the app explained"),
        ["docs.missing"]       = ("ملفّ الدليل غير موجود بجانب التطبيق.", "The guide file is missing next to the application."),
        ["docs.failed"]        = ("تعذّر فتح الدليل: {0}", "Could not open the guide: {0}"),

        // ===== اختصارات لوحة المفاتيح =====
        ["keys.nav"]           = ("الاختصارات", "Shortcuts"),
        ["keys.title"]         = ("اختصارات لوحة المفاتيح", "Keyboard shortcuts"),
        ["keys.hint"]          = ("انقر الاختصار ثمّ اضغط التركيبة الجديدة. Esc يلغي، وBackspace يعيد الافتراضيّ.",
                                  "Click a shortcut, then press the new combination. Esc cancels, Backspace restores the default."),
        ["keys.press"]         = ("اضغط التركيبة…", "Press keys…"),
        ["keys.reset"]         = ("أعد كلّ الاختصارات للافتراضيّ", "Reset all shortcuts"),
        ["keys.default"]       = ("افتراضيّ", "default"),
        ["keys.conflict"]      = ("{0} مستعمَل في «{1}» — اختر تركيبة أخرى.",
                                  "{0} is already used by \"{1}\" — pick another combination."),
        ["keys.changed"]       = ("«{0}» ← {1}", "\"{0}\" ← {1}"),
        ["keys.newTerminal"]   = ("تيرمنال جديد", "New terminal"),
        ["keys.splitV"]        = ("انقسام جنباً إلى جنب", "Split side by side"),
        ["keys.splitH"]        = ("انقسام فوق/تحت", "Split top/bottom"),
        ["keys.closePane"]     = ("إغلاق الجزء النشط", "Close active pane"),
        ["keys.palette"]       = ("لوحة الأوامر", "Command palette"),
        ["keys.aiPanel"]       = ("إظهار/إخفاء لوحة الذكاء", "Toggle AI panel"),
        ["keys.aiMode"]        = ("تبديل وضع الصندوق (أمر ⇄ ذكاء)", "Toggle box mode (command ⇄ AI)"),
        ["keys.search"]        = ("البحث في المخرجات", "Search the output"),
        ["keys.settings"]      = ("فتح الإعدادات", "Open settings"),
        ["ai.set.panelWidth"]  = ("عرض لوحة الذكاء", "AI panel width"),
        ["ai.set.chatFont"]    = ("حجم نصّ الدردشة", "Chat text size"),
        ["ai.panel.history"]   = ("الجلسات السابقة", "Previous sessions"),
        ["ai.panel.modelTip"]  = ("نموذج هذه الجلسة — لا يغيّر الإعداد المحفوظ",
                                  "Model for this session — does not change the saved setting"),
        ["ai.panel.modelSet"]  = ("نموذج هذه الجلسة: {0}", "Session model: {0}"),
        ["ai.panel.copyAll"]   = ("نسخ المحادثة", "Copy conversation"),
        ["ai.panel.copyCode"]  = ("نسخ", "Copy"),
        ["ai.panel.copied"]    = ("نُسخ", "Copied"),
        ["ai.panel.thinking"]  = ("يفكّر…", "Thinking…"),
        ["ai.tok.label"]       = ("توكنز", "tokens"),
        ["ai.tok.tip"]         = ("↑ توكنز الإدخال · ↓ توكنز الإخراج · Σ إجمالي الجلسة",
                                  "↑ input tokens · ↓ output tokens · Σ session total"),
        ["ai.panel.you"]       = ("أنت", "You"),
        ["ai.panel.closeWarn"] = ("هناك ردّ قيد الاستقبال. إغلاق التبويب سيلغيه.",
                                  "A reply is still streaming. Closing this tab will cancel it."),

        // بطاقة أوّل تشغيل: ثلاثة مسارات لا معالج متعدّد الخطوات.
        ["ai.first.title"]     = ("اربط مزوّداً لتبدأ", "Connect a provider to start"),
        ["ai.first.hint"]      = ("اختر مساراً — يمكن تغييره لاحقاً من الإعدادات.",
                                  "Pick a path — you can change it later in settings."),
        ["ai.first.cloud"]     = ("أدخل مفتاح مزوّد", "Enter a provider key"),
        ["ai.first.gateway"]   = ("مفتاح OpenRouter واحد لعشرات النماذج",
                                  "One OpenRouter key for dozens of models"),
        ["ai.first.local"]     = ("Ollama محلّي — بلا مفتاح", "Local Ollama — no key"),
        ["ai.first.localFound"]= ("وجدنا Ollama يعمل على جهازك", "Found Ollama running on this machine"),
        ["ai.first.localMiss"] = ("لم نجد Ollama يعمل الآن", "Ollama isn't running right now"),
        ["ai.first.later"]     = ("لاحقاً", "Later"),

        // ===== إعدادات الـ AI =====
        ["ai.set.title"]       = ("الذكاء الاصطناعي", "AI"),
        ["ai.set.provider"]    = ("المزوّد", "Provider"),
        ["ai.set.customProvider"] = ("مزوّد مخصّص", "Custom provider"),
        ["ai.set.model"]       = ("النموذج", "Model"),
        ["ai.set.refreshModels"]=("تحديث القائمة", "Refresh list"),
        ["ai.set.freeOnly"]    = ("المجّاني فقط", "Free only"),
        ["ai.set.modelCount"]  = ("{0} نموذجاً · {1} مجّانيّ", "{0} models · {1} free"),
        ["ai.set.modelCountNoPricing"] = ("{0} نموذجاً · التسعير غير متاح لدى هذا المزوّد",
                                          "{0} models · pricing not provided by this provider"),
        ["ai.set.noFreeModels"]= ("لا نماذج مجّانيّة لدى هذا المزوّد.", "No free models from this provider."),
        ["ai.set.key"]         = ("مفتاح الـ API", "API key"),
        ["ai.set.getKey"]      = ("احصل على مفتاح", "Get a key"),
        ["ai.set.test"]        = ("اختبار الاتّصال", "Test connection"),
        ["ai.set.testing"]     = ("جارٍ الاختبار…", "Testing…"),
        ["ai.set.baseUrl"]     = ("عنوان الخدمة (اختياريّ)", "Service URL (optional)"),
        ["ai.set.keyStored"]   = ("مفتاح محفوظ ومُعمّى على هذا الجهاز", "Key stored and encrypted on this device"),
        ["ai.set.keyMissing"]  = ("لا مفتاح بعد", "No key yet"),
        ["ai.set.keyReentry"]  = ("المفتاح مُعمّى على جهاز آخر — أعد إدخاله هنا",
                                  "Key was encrypted on another device — re-enter it here"),
        ["ai.set.noKeyNeeded"] = ("لا يحتاج مفتاحاً", "No key needed"),
        ["ai.set.learning"]    = ("التعلّم من استعمالي (محلّيّاً)", "Learn from my usage (locally)"),
        ["ai.set.learningHint"]= ("يبني قاعدة معرفة محلّيّة لترتيب الاقتراحات. لا يُرسَل شيء خارج جهازك.",
                                  "Builds a local knowledge base to rank suggestions. Nothing leaves your device."),
        ["ai.set.ambient"]     = ("إرسال سياق التبويب مع الدردشة", "Send tab context with chat"),
        ["ai.set.preview"]     = ("راجع قبل الإرسال", "Review before sending"),
        ["ai.set.quiet"]       = ("وضع هادئ (بلا رقاقات اقتراح)", "Quiet mode (no suggestion chips)"),
        ["ai.set.saveChats"]   = ("حفظ المحادثات على القرص", "Save conversations to disk"),
        ["ai.set.saveChatsHint"]=("معطَّل افتراضاً. عند التفعيل تُحفظ محادثاتك محلّيّاً بعد تنقيح الأسرار، ويمكن مسحها من «ذاكرة التطبيق».",
                                  "Off by default. When on, your chats are saved locally after redacting secrets, and can be erased from App Memory."),

        // مجموعات قسم الإعدادات
        ["ai.set.grpConnection"]=("الاتّصال", "Connection"),
        ["ai.set.grpBehavior"] = ("سلوك المساعد", "Assistant behavior"),
        ["ai.set.grpPrivacy"]  = ("الخصوصيّة والتعلّم", "Privacy & learning"),

        ["ai.set.temperature"] = ("درجة الإبداع", "Creativity (temperature)"),
        ["ai.set.temperatureHint"] = ("قيمة منخفضة = أوامر أدقّ وأقلّ تنوّعاً. الموصى به لعمل التيرمنال: 0.2–0.4.",
                                      "Lower = more precise, less varied commands. Recommended for terminal work: 0.2–0.4."),
        ["ai.set.maxTokens"]   = ("سقف طول الردّ", "Reply length cap"),
        ["ai.set.auto"]        = ("تلقائيّ", "Auto"),
        ["ai.set.ctxLimit"]    = ("سقف مقتطف السياق", "Context snippet cap"),
        ["ai.set.ctxLimitHint"]= ("أقصى عدد محارف من مخرجات التيرمنال تُرفَق مع السؤال.",
                                  "Maximum characters of terminal output attached to a question."),
        ["ai.set.customPrompt"]= ("تعليمات مخصّصة", "Custom instructions"),
        ["ai.set.customPromptHint"] = ("تُضاف إلى كلّ محادثة (مثل «استعمل PowerShell دائماً» أو «اشرح باختصار»). تُطبَّق على المحادثات الجديدة — امسح المحادثة لتفعيلها فوراً.",
                                       "Added to every conversation (e.g. \"always use PowerShell\" or \"be brief\"). Applies to new conversations — clear the chat to apply it now."),

        // ===== وضع الذكاء داخل صندوق الأوامر =====
        ["ai.cmp.modeCommand"] = ("أمر", "Command"),
        ["ai.cmp.modeAi"]      = ("ذكاء", "AI"),
        ["ai.cmp.hintCommand"] = ("اكتب أمراً…", "Type a command…"),
        ["ai.cmp.hintAi"]      = ("اطلب أيّ شيء — مثلاً: أنشئ فرعاً جديداً وادفعه",
                                  "Ask for anything — e.g. create a new branch and push it"),
        ["ai.cmp.switchTip"]   = ("تبديل الوضع (Ctrl+I). في وضع الذكاء يذهب ما تكتبه إلى المساعد مرفقاً بمجلد العمل والصدفة وآخر الأوامر.",
                                  "Switch mode (Ctrl+I). In AI mode what you type goes to the assistant along with the working directory, shell, and recent commands."),

        // شريط نتيجة الذكاء داخل التيرمنال
        ["ai.inline.ran"]      = ("نُفِّذ تلقائياً", "ran automatically"),
        ["ai.inline.run"]      = ("تشغيل", "Run"),
        ["ai.inline.edit"]     = ("تعديل", "Edit"),
        ["ai.inline.openChat"] = ("افتح المحادثة", "Open chat"),
        ["ai.inline.answerHint"]=("↓ أجب في الصندوق أدناه ليكمل", "↓ Answer in the box below to continue"),

        // أفعال كتلة الكود داخل لوحة الدردشة
        ["ai.code.run"]        = ("أرسل ونفّذ", "Send & run"),
        ["ai.code.send"]       = ("أرسل فقط", "Send only"),
        ["ai.panel.copiedChat"]=("نُسخت المحادثة", "Conversation copied"),
        ["ai.panel.searching"] = ("يبحث عن الإجابة", "Looking for an answer"),

        ["ai.set.autoRun"]     = ("نفّذ الأمر المقترَح تلقائياً", "Run the suggested command automatically"),
        ["ai.set.autoRunHint"] = ("في وضع الذكاء داخل صندوق الأوامر. الأوامر الخطرة والكتل متعدّدة الأسطر تُستثنى دائماً: تُعرض وتنتظر تأكيدك مهما كان هذا الخيار.",
                                  "In AI mode inside the command box. Risky commands and multi-line blocks are always excluded: they are shown and wait for your confirmation regardless of this setting."),

        // ===== بطاقة ترحيب «جلسة جديدة» =====
        ["ai.welcome.title"]   = ("جلسة تيرمنال جديدة", "New terminal session"),
        ["ai.welcome.aiMode"]  = ("التبديل بين وضع الأمر ووضع الذكاء", "switch between command mode and AI mode"),
        ["ai.welcome.history"] = ("استعراض أوامر الجلسة السابقة", "browse earlier commands in this session"),
        ["ai.welcome.search"]  = ("البحث داخل المخرجات", "search inside the output"),
        ["ai.welcome.complete"]= ("قبول الإكمال المقترَح", "accept the suggested completion"),
        ["ai.welcome.dismiss"] = ("لا تُظهر ثانيةً", "Don't show again"),

        // ===== أخطاء المزوّدين: رسالة بشريّة + إجراء =====
        ["ai.err.auth"]        = ("المفتاح غير صالح أو منتهي.", "The API key is invalid or expired."),
        ["ai.err.quota"]       = ("نفد رصيد الحساب أو حصّته لدى المزوّد.",
                                  "The account is out of credit or quota."),
        ["ai.err.rate"]        = ("تجاوزت حدّ المعدّل — انتظر قليلاً ثمّ أعد المحاولة.",
                                  "Rate limit reached — wait a moment and retry."),
        ["ai.err.rateWait"]    = ("تجاوزت حدّ المعدّل — أعد المحاولة بعد {0} ثانية.",
                                  "Rate limit reached — retry in {0}s."),
        ["ai.err.context"]     = ("السياق أطول ممّا يقبله هذا النموذج.",
                                  "The context is longer than this model accepts."),
        ["ai.err.model"]       = ("النموذج المختار غير متاح لدى هذا المزوّد.",
                                  "The selected model isn't available from this provider."),
        ["ai.err.network"]     = ("تعذّر الوصول إلى المزوّد — تحقّق من الاتّصال.",
                                  "Couldn't reach the provider — check your connection."),
        ["ai.err.timeout"]     = ("انتهت المهلة بلا استجابة.", "Timed out with no response."),
        ["ai.err.canceled"]    = ("أُلغي الطلب.", "Request cancelled."),
        ["ai.err.provider"]    = ("ردّ المزوّد بخطأ.", "The provider returned an error."),
        ["ai.err.noProvider"]  = ("لم يُربط مزوّد بعد — افتح الإعدادات لإضافة مفتاح.",
                                  "No provider connected yet — open settings to add a key."),
        // ===== معاينة ما سيُرسَل =====
        ["ai.prev.title"]      = ("هذا ما سيُرسَل", "This is what will be sent"),
        ["ai.prev.redacted"]   = ("حُجبت {0} عناصر — راجع قبل الإرسال",
                                  "{0} item(s) redacted — review before sending"),
        ["ai.prev.notSecret"]  = ("ليس سرّاً", "Not a secret"),
        ["ai.prev.allowed"]    = ("لن يُحجب", "Won't redact"),
        ["ai.prev.send"]       = ("أرسل", "Send"),
        ["ai.prev.cancel"]     = ("إلغاء", "Cancel"),

        // ===== أفعال السياق =====
        ["ai.ctx.explain"]     = ("اشرح هذا", "Explain this"),
        ["ai.ctx.explainFail"] = ("اشرح آخر خطأ", "Explain last error"),
        ["ai.ctx.fixFail"]     = ("أصلح آخر أمر فاشل", "Fix last failed command"),
        ["ai.ctx.toCommand"]   = ("حوّل إلى أمر", "Turn into a command"),
        ["ai.ctx.noFailed"]    = ("لا يوجد أمر فاشل بعد — يحتاج تكامل الصدفة (OSC 133).",
                                  "No failed command yet — needs shell integration (OSC 133)."),
        ["ai.ctx.askExplain"]  = ("اشرح ما حدث هنا وكيف أصلحه.",
                                  "Explain what happened here and how to fix it."),
        ["ai.ctx.askFix"]      = ("اقترح أمراً واحداً يصلح هذا الفشل. ضعه في كتلة كود.",
                                  "Suggest one command that fixes this failure. Put it in a code block."),
        ["ai.ctx.insert"]      = ("أدرج في سطر الإدخال", "Insert into the prompt"),
        ["ai.ctx.risky"]       = ("⚠ أمر خطر — راجعه قبل التنفيذ", "⚠ Risky command — review before running"),
        ["ai.ctx.inserted"]    = ("أُدرج — اضغط Enter لتنفيذه بنفسك",
                                  "Inserted — press Enter to run it yourself"),

        // ===== نافذة «ذاكرة التطبيق» =====
        ["ai.mem.title"]       = ("ذاكرة التطبيق", "App memory"),
        ["ai.mem.open"]        = ("ذاكرة التطبيق", "App memory"),
        ["ai.mem.subtitle"]    = ("كلّ ما تعلّمه التطبيق عن استعمالك — محفوظ على هذا الجهاز وحده، ولا يُرسَل إلى أيّ خدمة.",
                                  "Everything the app learned about your usage — stored on this device only, never sent anywhere."),
        ["ai.mem.stats"]       = ("{0} قالب أمر · نسبة قبول الاقتراحات {1} · حجم القاعدة {2} م.ب",
                                  "{0} command templates · suggestion acceptance {1} · database {2} MB"),
        ["ai.mem.tabCommands"] = ("أوامرك المتكرّرة", "Your frequent commands"),
        ["ai.mem.tabErrors"]   = ("الأخطاء وحلولها", "Errors and fixes"),
        ["ai.mem.tabSuggestions"] = ("سجلّ الاقتراحات", "Suggestion log"),
        ["ai.mem.colCommand"]  = ("القالب", "Template"),
        ["ai.mem.colRuns"]     = ("مرّات", "Runs"),
        ["ai.mem.colOutcome"]  = ("النتيجة", "Outcome"),
        ["ai.mem.colActions"]  = ("إجراءات", "Actions"),
        ["ai.mem.colError"]    = ("الخطأ", "Error"),
        ["ai.mem.colSolution"] = ("الحلّ المحفوظ", "Saved fix"),
        ["ai.mem.colSeen"]     = ("تكرار", "Seen"),
        ["ai.mem.colSuggestion"] = ("الاقتراح", "Suggestion"),
        ["ai.mem.colKind"]     = ("النوع", "Kind"),
        ["ai.mem.colVerdict"]  = ("القرار", "Verdict"),
        ["ai.mem.outcome"]     = ("{0} نجاح · {1} فشل", "{0} ok · {1} failed"),
        ["ai.mem.pin"]         = ("تثبيت", "Pin"),
        ["ai.mem.unpin"]       = ("إلغاء التثبيت", "Unpin"),
        ["ai.mem.ban"]         = ("حظر", "Ban"),
        ["ai.mem.unban"]       = ("رفع الحظر", "Unban"),
        ["ai.mem.delete"]      = ("حذف", "Delete"),
        ["ai.mem.noSolution"]  = ("لا حلّ محفوظ بعد", "No saved fix yet"),
        ["ai.mem.accepted"]    = ("قُبِل", "Accepted"),
        ["ai.mem.rejected"]    = ("رُفِض", "Rejected"),
        ["ai.mem.pending"]     = ("معلّق", "Pending"),
        ["ai.mem.tabProfile"]  = ("ملفّك التعريفيّ", "Your profile"),
        ["ai.mem.tabChats"]    = ("المحادثات", "Conversations"),
        ["ai.mem.colChatDate"] = ("الوقت", "When"),
        ["ai.mem.colChatTitle"]= ("المحادثة", "Conversation"),
        ["ai.mem.chatsEmpty"]  = ("لا محادثات محفوظة بعد — الحفظ مفعَّل، وأوّل محادثة تجريها ستظهر هنا.",
                                  "No saved conversations yet — saving is on, and your first conversation will appear here."),
        ["ai.mem.chatsOff"]    = ("حفظ المحادثات معطَّل، فلا شيء يُكتب على القرص. فعّله من: الإعدادات ← الذكاء الاصطناعي ← «حفظ المحادثات على القرص» — وعندها تظهر محادثاتك هنا.",
                                  "Conversation saving is off, so nothing is written to disk. Turn it on in Settings → AI → \"Save conversations to disk\" — then your conversations appear here."),
        ["ai.mem.profileEmpty"]= ("لا ملفّ بعد — يحتاج التطبيق بضعة أوامر متكرّرة قبل أن يستنتج شيئاً يستحقّ الإرسال.",
                                  "No profile yet — the app needs a few repeated commands before it has anything worth sending."),
        ["ai.mem.clearAll"]    = ("امسح كل شيء", "Erase everything"),
        ["ai.mem.clearConfirm"]= ("سيُحذف كلّ ما تعلّمه التطبيق: قوالب الأوامر وعدّاداتها، والأخطاء وحلولها، وسجلّ الاقتراحات. لا يمكن التراجع.",
                                  "This erases everything the app learned: command templates and counters, errors and fixes, and the suggestion log. This cannot be undone."),
        ["ai.mem.empty"]       = ("لا شيء هنا بعد. مع استعمالك للتيرمنال سيتعلّم التطبيق أوامرك المتكرّرة وأخطاءك الشائعة، فيرتّب الاقتراحات ويعرض حلولاً سبق أن قبلتها — كلّه محلّيّاً وبلا اتّصال.",
                                  "Nothing here yet. As you use the terminal the app learns your frequent commands and common errors, then ranks suggestions and recalls fixes you accepted — all locally, no connection needed."),

        // ===== جسر كتالوج الأوامر =====
        ["ai.cat.suggest"]     = ("نفّذت هذا الأمر {0} مرّة — تحفظه في الأوامر المحفوظة؟",
                                  "You've run this {0} times — save it to your commands?"),
        ["ai.cat.save"]        = ("احفظه", "Save it"),
        ["ai.cat.dismiss"]     = ("لا، شكراً", "No thanks"),
        ["ai.cat.saved"]       = ("حُفظ في الأوامر المحفوظة.", "Saved to your commands."),
        ["ai.cat.namePrompt"]  = ("اسم الأمر المحفوظ:", "Name for the saved command:"),

        // ===== معالج تكامل الصدفة (OSC 133) =====
        ["ai.osc.title"]       = ("تفعيل تكامل الصدفة", "Enable shell integration"),
        ["ai.osc.explain"]     = ("لتعرف الأداة أين يبدأ كلّ أمر وأين ينتهي وما رمز خروجه (فتعمل «أصلح آخر فاشل» ورقاقة الأخطاء وعمود النجاح/الفشل)، تُضاف خطافات OSC 133 إلى ملفّ بروفايل صدفتك. هذا ما سيُضاف حرفياً:",
                                  "So the app knows where each command begins and ends and its exit code (enabling \"fix last failure\", the error chip, and the success/fail column), OSC 133 hooks are added to your shell profile. Here is exactly what will be added:"),
        ["ai.osc.copy"]        = ("انسخه بنفسي", "Copy it myself"),
        ["ai.osc.copied"]      = ("نُسخ إلى الحافظة — الصقه في ملفّ بروفايل صدفتك.", "Copied — paste it into your shell profile."),
        ["ai.osc.install"]     = ("حقن تلقائيّ", "Install automatically"),
        ["ai.osc.installed"]   = ("التكامل مثبَّت أصلاً في هذا البروفايل.", "Integration is already installed in this profile."),
        ["ai.osc.notInstalled"]= ("غير مثبَّت بعد.", "Not installed yet."),
        ["ai.osc.willCreate"]  = ("ملفّ البروفايل غير موجود — سيُنشأ.", "The profile file doesn't exist — it will be created."),
        ["ai.osc.confirm"]     = ("سيُضاف الخطاف إلى نهاية ملفّ بروفايل صدفتك، مع نسخة احتياطية منه أوّلاً. محتواك الحاليّ لا يُمَسّ. متابعة؟",
                                  "The hook will be appended to the end of your shell profile, with a backup taken first. Your existing content is untouched. Continue?"),
        ["ai.osc.done"]        = ("✓ تمّ الحقن.", "✓ Installed."),
        ["ai.osc.backup"]      = ("نسخة احتياطية: {0}", "Backup: {0}"),
        ["ai.osc.restart"]     = ("افتح تبويباً جديداً (أو أعد تشغيل الصدفة) ليسري المفعول.", "Open a new tab (or restart the shell) for it to take effect."),
        ["ai.osc.cta"]         = ("فعّل تكامل الصدفة", "Enable shell integration"),
        ["ai.osc.unsupported"] = ("هذه الصدفة لا تدعم الحقن التلقائيّ بعد.", "This shell doesn't support automatic install yet."),

        // ===== رقاقة الخطأ =====
        ["ai.chip.explain"]    = ("اشرح هذا الخطأ؟", "Explain this error?"),
        ["ai.chip.seenBefore"] = ("رأيت هذا من قبل — الحل السابق", "Seen before — previous fix"),
        ["ai.chip.dismiss"]    = ("إخفاء", "Dismiss"),

        ["ai.act.settings"]    = ("افتح الإعدادات", "Open settings"),
        ["ai.act.retry"]       = ("أعد المحاولة", "Retry"),
        ["ai.act.billing"]     = ("صفحة الفوترة", "Billing page"),
        ["ai.act.trim"]        = ("قلّص السياق", "Trim context"),
    };
}
