using System;
using System.Collections.Generic;
using System.Windows;

namespace TerminalLauncher.Services;

/// <summary>لغة الواجهة.</summary>
public enum AppLang { Ar, En }

/// <summary>
/// تعريب بسيط وقت التشغيل (عربي/إنجليزي) + اتجاه الواجهة (RTL/LTR).
/// القيم مُضمّنة كأزواج (عربي، إنجليزي)؛ الطبقات تستدعي <see cref="T"/> بمفتاح.
/// </summary>
public static class Loc
{
    public static AppLang Current { get; private set; } = AppLang.Ar;

    /// <summary>يُطلَق عند تغيّر اللغة (تُعيد الطبقات تطبيق النصوص/الاتجاه).</summary>
    public static event Action? Changed;

    /// <summary>اتجاه الواجهة الموافق للّغة الحاليّة.</summary>
    public static FlowDirection Flow => Current == AppLang.Ar ? FlowDirection.RightToLeft : FlowDirection.LeftToRight;

    /// <summary>رمز اللغة للحفظ ("ar"/"en").</summary>
    public static string Code => Current == AppLang.En ? "en" : "ar";

    /// <summary>يضبط اللغة من رمز محفوظ دون إطلاق الحدث (للتهيئة).</summary>
    public static void InitFromCode(string? code)
        => Current = string.Equals(code, "en", StringComparison.OrdinalIgnoreCase) ? AppLang.En : AppLang.Ar;

    /// <summary>يبدّل اللغة ويُطلِق <see cref="Changed"/>.</summary>
    public static void Set(AppLang lang)
    {
        if (Current == lang) return;
        Current = lang;
        Changed?.Invoke();
    }

    /// <summary>النصّ الموافق للّغة الحاليّة (يعيد المفتاح نفسه إن لم يُعرَّف).</summary>
    public static string T(string key)
        => Table.TryGetValue(key, out var pair) ? (Current == AppLang.En ? pair.En : pair.Ar) : key;

    private static readonly Dictionary<string, (string Ar, string En)> Table = new()
    {
        ["app.title"]          = ("مشغّل الأوامر", "Command Launcher"),
        ["sidebar.saved"]      = ("الأوامر المحفوظة", "Saved commands"),
        ["sidebar.search"]     = ("بحث…", "Search…"),
        ["btn.run"]            = ("▶  تشغيل", "▶  Run"),
        ["hint.pick"]          = ("اختر أمراً واضغط «تشغيل» لفتح تيرمنال", "Pick a command and press Run to open a terminal"),
        // لوحة البداية: عنوان + وصف كلّ اختصار بجوار رقاقاته.
        ["hint.title"]         = ("جلسة تيرمنال جديدة", "New terminal session"),
        ["hint.palette"]       = ("لوحة الأوامر", "command palette"),
        ["hint.splitV"]        = ("انقسام جنباً لجنب", "split side by side"),
        ["hint.splitH"]        = ("انقسام فوق/تحت", "split top/bottom"),
        ["sidebar.projects"]   = ("المشاريع", "Projects"),
        // يُعرض بجوار رقاقات الكيبورد (ctrl shift T) فلا يذكر الاختصار نصّاً.
        ["hint.empty"]         = ("تيرمنال فارغ", "new empty terminal"),
        // النصّ البديل في حقل البحث المركزيّ بشريط العنوان (يفتح لوحة البحث المتقدّم).
        ["hdr.search"]         = ("ابحث في كل شيء…", "Search everything…"),

        // لوحة البحث المتقدّم: عناوين الأقسام ورقاقات الفئات.
        ["palette.suggested"]  = ("مقترَح", "Suggested"),
        ["palette.results"]    = ("النتائج ({0})", "Results ({0})"),
        ["palette.cat.actions"]  = ("أفعال", "actions"),
        ["palette.cat.projects"] = ("مشاريع", "projects"),
        ["palette.cat.commands"] = ("أوامر", "commands"),
        ["palette.cat.tabs"]     = ("تبويبات", "tabs"),
        ["palette.cat.shells"]   = ("صدفات", "shells"),
        ["settings.title"]     = ("الإعدادات", "Settings"),
        ["settings.appearance"]= ("المظهر", "Appearance"),
        ["settings.theme"]     = ("الثيم", "Theme"),
        ["settings.themehint"] = ("اختر ثيماً — يُطبَّق فوراً", "Pick a theme — applied instantly"),
        ["settings.showAllThemes"] = ("عرض كل الثيمات", "Show all themes"),
        ["settings.allThemes"] = ("كل الثيمات", "All themes"),
        ["tip.toggleSidebar"]  = ("إظهار/إخفاء الأوامر المحفوظة", "Show/hide saved commands"),
        ["settings.syncos"]    = ("مزامنة الفاتح/الداكن مع النظام", "Sync light/dark with OS"),
        ["settings.dark"]      = ("داكن", "Dark"),
        ["settings.light"]     = ("فاتح", "Light"),
        ["settings.accent"]    = ("لون التمييز", "Accent color"),
        ["settings.fontsize"]  = ("حجم خطّ التيرمنال", "Terminal font size"),
        ["settings.fontfamily"]= ("نوع الخطّ", "Font family"),
        ["settings.terminalFont"] = ("خطّ الطرفية (التيرمنال)", "Terminal font"),
        ["settings.uiFonts"]   = ("خطوط الواجهة", "Interface fonts"),
        ["settings.uiFamily"]  = ("خطّ الواجهة (اسم خطّ مثبَّت — فارغ = الافتراضيّ)", "UI font (installed font name — blank = default)"),
        ["settings.monoFamily"]= ("الخطّ أحاديّ العرض (المسارات/النصوص التقنيّة)", "Monospace font (paths / technical text)"),
        ["settings.uiSize"]    = ("حجم نصّ الواجهة", "UI text size"),
        ["settings.menuSize"]  = ("حجم القوائم", "Menu size"),
        ["settings.tableSize"] = ("حجم الجداول", "Table size"),
        ["settings.titleSize"] = ("حجم العناوين", "Title size"),
        ["settings.openJson"]  = ("فتح ملف الإعدادات (JSON)", "Open settings file (JSON)"),
        ["settings.editConfig"] = ("محرّر الإعدادات", "Config editor"),
        ["settings.applyJson"] = ("إعادة تحميل الملف", "Reload file"),
        ["settings.resetFont"] = ("استعادة الافتراضي", "Reset to default"),
        ["settings.cornerRadius"] = ("استدارة الحواف", "Corner radius"),
        ["settings.fontsHint"] = ("تُحفَظ في config.json وتُطبَّق فوراً. استعمل «محرّر الإعدادات» للتعديل بأمان.", "Saved to config.json and applied instantly. Use the Config editor to edit safely."),
        // ===== محرّر الإعدادات الذكيّ =====
        ["cfg.title"]          = ("محرّر الإعدادات", "Config editor"),
        ["cfg.tab.ui"]         = ("الواجهة (config.json)", "Interface (config.json)"),
        ["cfg.tab.system"]     = ("النظام", "System"),
        ["cfg.format"]         = ("تنسيق", "Format"),
        ["cfg.validate"]       = ("تحقّق", "Validate"),
        ["cfg.save"]           = ("حفظ وتطبيق", "Save & apply"),
        ["cfg.reload"]         = ("إعادة تحميل", "Reload"),
        ["cfg.close"]          = ("إغلاق", "Close"),
        ["cfg.valid"]          = ("صياغة سليمة ✓", "Valid syntax ✓"),
        ["cfg.saved"]          = ("حُفِظ وطُبِّق ✓", "Saved & applied ✓"),
        ["cfg.savedRestart"]   = ("حُفِظ ✓ — أعد التشغيل لتطبيق إعدادات النظام", "Saved ✓ — restart to apply system settings"),
        ["cfg.formatted"]      = ("نُسِّق ✓", "Formatted ✓"),
        ["cfg.errAt"]          = ("خطأ عند السطر {0}، العمود {1}: {2}", "Error at line {0}, column {1}: {2}"),
        ["cfg.errSave"]        = ("تعذّر الحفظ: {0}", "Save failed: {0}"),
        ["cfg.cantSaveInvalid"] = ("لا يمكن الحفظ: صحّح أخطاء الصياغة أوّلاً", "Cannot save: fix syntax errors first"),
        ["cfg.systemHint"]     = ("إعدادات النظام (الثيم/اللغة/الخلفية). تُطبَّق بعد إعادة التشغيل.", "System settings (theme/language/background). Applied after restart."),
        ["settings.textcolor"] = ("لون الكتابة", "Text color"),
        ["settings.language"]  = ("اللغة", "Language"),
        ["settings.background"] = ("الخلفية", "Background"),
        ["settings.font"]       = ("الخطّ", "Font"),
        ["settings.appearanceBg"] = ("المظهر والخلفية", "Appearance & Background"),
        ["settings.langFont"]     = ("اللغة والخطّ", "Language & Font"),
        ["settings.autosave"]  = ("تُحفظ التفضيلات تلقائياً", "Preferences are saved automatically"),

        // ===== الخلفيّة (قوالب + صورة + شفافيّة التيرمنال) =====
        ["bg.section"]         = ("الخلفية", "Background"),
        ["bg.templates"]       = ("قوالب", "Templates"),
        ["bg.solids"]          = ("ألوان مصمتة", "Solid colors"),
        ["bg.gradients"]       = ("تدرّجات", "Gradients"),
        ["bg.patterns"]        = ("نقوش", "Patterns"),
        ["bg.themeDefault"]    = ("خلفية الثيم", "Theme default"),
        ["bg.custom"]          = ("صورة مخصّصة", "Custom image"),
        ["bg.choose"]          = ("اختر صورة", "Choose image"),
        ["bg.clear"]           = ("إزالة", "Remove"),
        ["bg.opacity"]         = ("شفافية التيرمنال", "Terminal opacity"),
        ["tip.newtab"]         = ("تيرمنال فارغ جديد (Ctrl+Shift+T)", "New empty terminal (Ctrl+Shift+T)"),
        ["tip.history"]        = ("سجلّ الأوامر", "Command history"),
        ["tip.settings"]       = ("الإعدادات", "Settings"),
        // وسوم نوع الاقتراح في صندوق التأليف (تُعرَض كحبّة صغيرة يمين كلّ عنصر).
        ["sug.command"]        = ("أمر", "command"),
        ["sug.subcommand"]     = ("أمر فرعيّ", "subcommand"),
        ["sug.flag"]           = ("خيار", "flag"),
        ["sug.folder"]         = ("مجلد", "folder"),
        ["sug.file"]           = ("ملفّ", "file"),
        ["sug.branch"]         = ("فرع", "branch"),
        ["sug.script"]         = ("سكربت", "script"),
        ["sug.process"]        = ("عمليّة", "process"),
        ["sug.history"]        = ("سجلّ", "history"),
        // متصفّح المجلدات (زرّ الباث فوق الإنبت).
        ["cwd.parent"]         = (".. (المجلد الأعلى)", ".. (Parent Directory)"),
        ["cwd.search"]         = ("ابحث في المجلدات…", "Search directories…"),
        ["tip.cwdPicker"]      = ("تصفّح المجلدات (cd)", "Browse folders (cd)"),
        ["tip.add"]            = ("إضافة أمر", "Add command"),
        ["profiles.manage"]    = ("إدارة البروفايلات…", "Manage profiles…"),
        // {0} = العدد الكلّيّ للصدفات المتاحة.
        ["profiles.showAll"]   = ("عرض كل الصدفات ({0})…", "Show all shells ({0})…"),

        // ===== تأكيد اللصق (حماية) =====
        ["paste.title"]        = ("تأكيد اللصق", "Confirm paste"),
        ["paste.warnMulti"]    = ("أنت على وشك لصق نصّ متعدّد الأسطر في التيرمنال. راجعه قبل التنفيذ:",
                                  "You are about to paste multi-line text into the terminal. Review it before running:"),
        ["paste.warnDanger"]   = ("⚠ يحتوي النصّ الملصوق على أوامر قد تكون خطرة. راجعه بعناية قبل اللصق:",
                                  "⚠ The pasted text contains commands that may be dangerous. Review it carefully before pasting:"),
        ["paste.confirm"]      = ("لصق", "Paste"),
        ["paste.cancel"]       = ("إلغاء", "Cancel"),
        ["paste.lines"]        = ("سطر", "lines"),

        // ===== لوحة «ما الجديد» (What's New) =====
        ["whatsnew.title"]     = ("ما الجديد", "What's New"),
        ["whatsnew.empty"]     = ("لا توجد مستجدّات لعرضها.", "No changes to show yet."),
        ["whatsnew.highlights"]= ("أبرز المميّزات", "Highlights"),
        ["whatsnew.section.new"]      = ("جديد", "New"),
        ["whatsnew.section.improved"] = ("تحسينات", "Improved"),
        ["whatsnew.section.fixed"]    = ("إصلاحات", "Fixed"),
        ["tip.whatsnew"]       = ("ما الجديد / حول البرنامج", "What's New / About"),
        ["common.close"]       = ("إغلاق", "Close"),

        // ===== لوحة المشاريع + الدوك =====
        ["sidebar.projects"]   = ("المشاريع", "Projects"),
        ["proj.open"]          = ("▶  فتح المشروع", "▶  Open project"),
        ["proj.search"]        = ("بحث في المشاريع…", "Search projects…"),
        ["proj.new"]           = ("مشروع جديد", "New project"),
        ["proj.edit"]          = ("تعديل المشروع", "Edit project"),
        ["proj.noFolder"]      = ("بلا فولدر — اضغط لتحديده", "No folder — click to set"),
        ["proj.steps"]         = ("خطوات", "steps"),
        ["proj.field.name"]    = ("الاسم", "Name"),
        ["proj.field.tags"]    = ("التاكات (تصنيفات ملوّنة)", "Tags (colored labels)"),
        ["proj.field.folder"]  = ("الباث (مجلّد العمل)", "Path (working directory)"),
        ["proj.filter.all"]    = ("الكل", "All"),
        ["proj.noTags"]        = ("لا تاكات بعد — أنشئ تاكاً بالأسفل", "No tags yet — create one below"),
        ["proj.field.shell"]   = ("الصدفة الافتراضية", "Default shell"),
        ["proj.folder.browse"] = ("اختر الفولدر", "Choose folder"),
        ["proj.cmd.new"]       = ("＋ أمر جديد", "＋ New command"),
        ["proj.cmd.edit"]      = ("تعديل الأمر", "Edit command"),
        ["proj.cmd.labelHint"] = ("اسم الأمر (اختياريّ)", "Command name (optional)"),
        ["proj.cmd.stepsHint"] = ("أمر في كلّ سطر — تُنفَّذ بالتوالي", "One command per line — run in sequence"),
        ["proj.cmd.folderHint"]= ("فولدر خاصّ (اختياريّ)", "Override folder (optional)"),
        // ليبلات محرّر الأمر المضمّن (فوق كلّ حقل).
        ["proj.cmd.labelLbl"]  = ("الاسم", "Name"),
        ["proj.cmd.stepsLbl"]  = ("الأوامر", "Commands"),
        ["proj.cmd.folderLbl"] = ("الفولدر", "Folder"),
        ["quick.addCurrent"]   = ("＋ أضف الأمر الحاليّ من التيرمنال", "＋ Add current command from terminal"),
        ["quick.remove"]       = ("حذف الأمر", "Remove command"),
        ["quick.empty"]        = ("لا أوامر بعد — اضغط «＋ أمر جديد» أو «أضف الأمر الحاليّ».",
                                  "No commands yet — press “＋ New command” or “Add current command”."),
        ["quick.added"]        = ("أُضيف الأمر للمشروع", "Command added to project"),
        ["quick.duplicate"]    = ("الأمر موجود مسبقاً — لم يُضَف", "Command already exists — not added"),
        ["quick.noCurrent"]    = ("لا يوجد أمر حاليّ في التيرمنال النشط", "No current command in the active terminal"),
        ["quick.noTerminal"]   = ("افتح تيرمنالاً أولاً لتشغيل الأمر", "Open a terminal first to run the command"),

        // ===== فتح المسار + محرّر الملفّ داخل التاب (T-7) =====
        ["menu.openFolder"]    = ("فتح المجلّد", "Open folder"),
        ["menu.openFile"]      = ("فتح الملفّ", "Open file"),
        ["editor.save"]        = ("حفظ", "Save"),
        ["editor.dontSave"]    = ("عدم الحفظ", "Don't save"),
        ["editor.cancel"]      = ("إلغاء", "Cancel"),
        ["editor.unsavedTitle"]= ("تغييرات غير محفوظة", "Unsaved changes"),
        ["editor.unsavedMessage"]=("توجد تغييرات غير محفوظة في هذا الملفّ. هل تريد حفظها قبل الإغلاق؟",
                                   "This file has unsaved changes. Do you want to save them before closing?"),

        // ===== مراقب الخوادم (Server Monitor) =====
        ["srv.title"]          = ("مراقب الخوادم", "Server Monitor"),
        ["tip.serverMonitor"]  = ("مراقب الخوادم (تخزين وأداء عبر SSH)", "Server Monitor (storage & performance over SSH)"),
        ["srv.servers"]        = ("الخوادم", "Servers"),
        ["srv.search"]         = ("بحث…", "Search…"),
        ["srv.add"]            = ("إضافة خادم", "Add server"),
        ["srv.edit"]           = ("تعديل", "Edit"),
        ["srv.delete"]         = ("حذف", "Delete"),
        ["srv.duplicate"]      = ("نسخ", "Duplicate"),
        ["srv.connect"]        = ("اتّصال", "Connect"),
        ["srv.disconnect"]     = ("قطع الاتّصال", "Disconnect"),
        ["srv.reconnect"]      = ("إعادة الاتّصال", "Reconnect"),
        ["srv.test"]           = ("اختبار الاتّصال", "Test connection"),
        ["srv.refresh"]        = ("تحديث", "Refresh"),
        ["srv.noServers"]      = ("لا خوادم بعد — أضِف خادماً للبدء", "No servers yet — add one to begin"),
        ["srv.pickServer"]     = ("اختر خادماً واضغط «اتّصال»", "Pick a server and press Connect"),
        ["srv.status.idle"]    = ("غير متّصل", "Disconnected"),
        ["srv.status.connecting"] = ("جارٍ الاتّصال…", "Connecting…"),
        ["srv.status.connected"]  = ("متّصل", "Connected"),
        ["srv.status.failed"]  = ("فشل الاتّصال", "Connection failed"),
        ["srv.status.reconnecting"] = ("انقطع الاتّصال — إعادة الاتّصال…", "Connection lost — reconnecting…"),
        ["srv.lastConnected"]  = ("آخر اتّصال", "Last connected"),
        ["srv.never"]          = ("أبداً", "Never"),
        ["srv.disks"]          = ("الأقراص والمساحة", "Disks & storage"),
        ["srv.col.mount"]      = ("نقطة التركيب", "Mount"),
        ["srv.col.size"]       = ("الحجم", "Size"),
        ["srv.col.used"]       = ("المستخدم", "Used"),
        ["srv.col.avail"]      = ("الفارغ", "Free"),
        ["srv.col.usePct"]     = ("النسبة", "Use%"),
        ["srv.testOk"]         = ("نجح الاتّصال بالخادم.", "Connection succeeded."),
        ["srv.testFail"]       = ("تعذّر الاتّصال بالخادم:", "Could not connect:"),

        // محرّر بروفايل الخادم
        ["srv.ed.addTitle"]    = ("إضافة خادم", "Add server"),
        ["srv.ed.editTitle"]   = ("تعديل الخادم", "Edit server"),
        ["srv.ed.name"]        = ("الاسم", "Name"),
        ["srv.ed.host"]        = ("المضيف (Host/IP)", "Host / IP"),
        ["srv.ed.port"]        = ("المنفذ", "Port"),
        ["srv.ed.user"]        = ("اسم المستخدم", "Username"),
        ["srv.ed.auth"]        = ("المصادقة", "Authentication"),
        ["srv.ed.authPassword"]= ("كلمة مرور", "Password"),
        ["srv.ed.authKey"]     = ("مفتاح خاصّ", "Private key"),
        ["srv.ed.password"]    = ("كلمة المرور", "Password"),
        ["srv.ed.key"]         = ("المفتاح الخاصّ (PEM)", "Private key (PEM)"),
        ["srv.ed.keyPass"]     = ("عبارة مرور المفتاح", "Key passphrase"),
        ["srv.ed.secretKept"]  = ("(محفوظ — اتركه فارغاً للإبقاء عليه)", "(saved — leave blank to keep)"),
        ["srv.ed.color"]       = ("لون مميّز", "Accent color"),
        ["srv.ed.notes"]       = ("ملاحظات", "Notes"),
        ["srv.ed.save"]        = ("حفظ", "Save"),
        ["srv.ed.cancel"]      = ("إلغاء", "Cancel"),
        ["srv.ed.ok"]          = ("حسناً", "OK"),
        ["srv.ed.deleteConfirm"] = ("سيُحذف هذا الخادم نهائيّاً. لا يمكن التراجع عن هذا.", "This server will be permanently deleted. This can’t be undone."),

        // مستكشف المجلّدات (الموجة 2)
        ["srv.tab.dashboard"]  = ("لوحة القيادة", "Dashboard"),
        ["srv.tab.disks"]      = ("الأقراص", "Disks"),
        ["srv.tab.folders"]    = ("المجلّدات", "Folders"),

        // لوحة القيادة
        ["srv.dash.overview"]  = ("نظرة عامّة", "Overview"),
        ["srv.dash.topProc"]   = ("أعلى العمليّات", "Top processes"),
        ["srv.dash.treemap"]   = ("استهلاك المجلّدات (Treemap)", "Folders Usage (Treemap)"),
        ["srv.dash.largest"]   = ("أكبر الملفّات", "Largest Files"),
        ["srv.dash.loadLargest"] = ("عرض أكبر الملفّات", "Load largest files"),
        ["srv.dash.tree"]      = ("الشجرة", "Tree"),
        ["srv.dash.host"]      = ("المضيف", "Host"),
        ["srv.dash.os"]        = ("النظام", "OS"),
        ["srv.dash.kernel"]    = ("النواة", "Kernel"),
        ["srv.dash.cpu"]       = ("المعالج", "CPU"),
        ["srv.dash.ip"]        = ("العنوان", "IP"),
        ["srv.dash.cores"]     = ("نواة", "cores"),
        ["srv.dash.uptime"]    = ("التشغيل", "Uptime"),
        ["srv.dash.load"]      = ("الحِمل (1د)", "Load (1m)"),
        ["srv.dash.ram"]       = ("الذاكرة", "Memory"),
        ["srv.dash.rootDisk"]  = ("القرص /", "Disk /"),
        ["srv.live.toggle"]    = ("● مباشر", "● Live"),
        ["srv.live.updated"]   = ("آخر تحديث:", "Updated:"),
        ["srv.alert.diskFull"] = ("امتلاء قرص", "Disk almost full"),
        ["srv.alert.highLoad"] = ("حِمل عالٍ", "High load"),
        ["srv.folder.scan"]    = ("فحص", "Scan"),
        ["srv.folder.copyPath"]= ("نسخ المسار", "Copy path"),
        ["srv.folder.favorites"] = ("المفضّلة", "Favorites"),
        ["srv.folder.total"]   = ("الإجماليّ", "Total"),
        ["srv.folder.subfolders"] = ("مجلّد فرعيّ", "subfolders"),
        ["srv.folder.empty"]   = ("لا مجلّدات فرعيّة", "No subfolders"),
        ["srv.folder.loading"] = ("جارٍ الفحص…", "Scanning…"),
        ["srv.folder.pathHint"]= ("مسار مطلق (مثل /var)", "Absolute path (e.g. /var)"),
        ["srv.tree.openFiles"] = ("عرض الملفّات هنا", "Show files here"),
        ["srv.tree.openFolders"] = ("فتح في المجلّدات", "Open in Folders"),
        ["srv.tree.refresh"]   = ("تحديث المجلّد", "Refresh folder"),
        ["srv.tree.deleteFolder"] = ("حذف المجلّد", "Delete folder"),
        ["srv.tree.deleteFolderConfirm"] = ("حذف هذا المجلّد وكلّ محتوياته نهائيّاً؟ لا يمكن التراجع.",
                                            "Delete this folder and all its contents permanently? This cannot be undone."),
        ["srv.tree.cantDeleteRoot"] = ("لا يمكن حذف الجذر.", "Cannot delete the root folder."),
        ["srv.tree.upload"]    = ("رفع ملفّات هنا", "Upload files here"),
        ["srv.tree.newFolder"] = ("مجلّد جديد", "New folder"),
        ["srv.tree.folderCreated"] = ("تمّ إنشاء المجلّد", "Folder created"),
        ["srv.up.title"]       = ("رفع", "Upload"),
        ["srv.up.uploading"]   = ("جارٍ الرفع", "Uploading"),
        ["srv.up.cancelled"]   = ("أُلغي الرفع", "Upload cancelled"),
        ["srv.file.deleteManyConfirm"] = ("ستُحذف الملفّات المحدّدة نهائيّاً. لا يمكن التراجع.", "The selected files will be permanently deleted. This can’t be undone."),

        // الملفّات والعمليّات (الموجة 3)
        ["srv.tab.files"]      = ("الملفّات", "Files"),
        ["srv.tab.mgmt"]       = ("الإدارة", "Manage"),
        ["srv.tab.containers"] = ("الحاويات", "Containers"),
        ["srv.containers.title"] = ("حاويات Docker", "Docker containers"),
        ["srv.containers.none"] = ("لا حاويات على هذا الخادم (أو Docker غير مثبّت/بلا صلاحية).", "No containers on this server (or Docker is not installed / no permission)."),
        ["srv.containers.nameTitle"] = ("تسمية الحاوية", "Name container"),
        ["srv.containers.search"] = ("بحث في الحاويات…", "Search containers…"),
        ["srv.containers.enter"] = ("فتح", "Open"),
        ["srv.containers.rename"] = ("تسمية…", "Rename…"),
        ["srv.containers.clearName"] = ("إزالة الاسم", "Clear name"),
        ["srv.containers.noMatch"] = ("لا نتائج مطابقة للبحث.", "No containers match the search."),
        ["srv.ed.sudo"] = ("استخدم sudo لأوامر Docker", "Use sudo for Docker commands"),
        ["srv.ed.sudoHint"] = ("لِلمستخدمين بلا صلاحيّة docker مباشرة. السرد يحتاج sudo بلا كلمة مرور (NOPASSWD)؛ الكونسول يطلب كلمة المرور داخل التبويب عند الحاجة.", "For users without direct docker access. Listing needs passwordless sudo (NOPASSWD); the console prompts for the password inside the tab if required."),
        ["srv.explorer.title"] = ("مستكشف الحاوية", "Container explorer"),
        ["srv.explorer.consoleHere"] = ("الكونسول هنا", "Console here"),
        ["srv.explorer.empty"] = ("مجلّد فارغ", "Empty folder"),
        ["srv.explorer.copy"] = ("نسخ", "Copy"),
        ["srv.explorer.open"] = ("فتح", "Open"),
        ["srv.explorer.download"] = ("تنزيل…", "Download…"),
        ["srv.explorer.console"] = ("الكونسول", "Console"),
        ["srv.explorer.redock"] = ("إرجاع للواجهة", "Dock back"),
        ["srv.explorer.rename"] = ("إعادة تسمية", "Rename"),
        ["srv.explorer.delete"] = ("حذف", "Delete"),
        ["srv.explorer.delConfirm"] = ("سيُحذف هذا الملفّ نهائيّاً. لا يمكن التراجع.", "This file will be permanently deleted. This can’t be undone."),
        ["srv.explorer.delDirConfirm"] = ("سيُحذف هذا المجلّد بمحتوياته نهائيّاً. لا يمكن التراجع.", "This folder and its contents will be permanently deleted. This can’t be undone."),
        ["srv.explorer.newFolder"] = ("مجلّد جديد", "New folder"),
        ["srv.explorer.namePlaceholder"] = ("الاسم", "Name"),
        ["srv.explorer.upload"] = ("رفع ملفّ", "Upload file"),
        ["srv.explorer.edit"] = ("تعديل", "Edit"),
        ["srv.explorer.save"] = ("حفظ", "Save"),
        ["srv.explorer.saved"] = ("تمّ الحفظ.", "Saved."),
        ["srv.explorer.customShell"] = ("أمر مخصّص", "Custom command"),
        ["srv.explorer.view.binary"] = ("ملفّ ثنائيّ — لا يمكن عرضه كنصّ.", "Binary file — cannot be shown as text."),
        ["srv.explorer.view.truncated"] = ("عُرِض أوّل 512KB فقط (الملفّ أكبر).", "Showing first 512KB only (file is larger)."),

        // ترويسات أعمدة قائمة الملفّات (قابلة للنقر للفرز)
        ["srv.explorer.colName"]     = ("الاسم", "Name"),
        ["srv.explorer.colType"]     = ("النوع", "Type"),
        ["srv.explorer.colSize"]     = ("الحجم", "Size"),
        ["srv.explorer.colModified"] = ("عُدِّل", "Modified"),

        // أنواع المداخل في مستكشف الحاوية (نصّ مترجَم بدل الامتداد الخام)
        ["srv.type.folder"]  = ("مجلّد", "Folder"),
        ["srv.type.link"]    = ("رابط", "Link"),
        ["srv.type.file"]    = ("ملفّ", "File"),
        ["srv.type.text"]    = ("نصّ", "Text"),
        ["srv.type.data"]    = ("بيانات", "Data"),
        ["srv.type.code"]    = ("شفرة", "Code"),
        ["srv.type.image"]   = ("صورة", "Image"),
        ["srv.type.archive"] = ("أرشيف", "Archive"),
        ["srv.type.video"]   = ("فيديو", "Video"),
        ["srv.type.audio"]   = ("صوت", "Audio"),
        ["srv.type.web"]     = ("صفحة ويب", "Web page"),
        ["srv.type.binary"]  = ("ثنائيّ", "Binary"),
        ["srv.type.doc"]     = ("مستند", "Document"),

        // أزرار الحوارات + حوارات الحذف في النافذة الرئيسيّة (تُراعي اللغة)
        ["dlg.cancel"] = ("إلغاء", "Cancel"),
        ["dlg.delete"] = ("حذف", "Delete"),
        ["dlg.save"]   = ("حفظ", "Save"),
        ["ctx.open"]   = ("فتح", "Open"),
        ["ctx.edit"]   = ("تعديل", "Edit"),
        ["ctx.download"] = ("تنزيل…", "Download…"),
        ["ctx.rename"] = ("إعادة تسمية…", "Rename…"),
        ["ctx.consoleHere"] = ("الكونسول هنا", "Console here"),
        ["ctx.close"]  = ("إغلاق", "Close"),
        ["dlg.proj.title"]   = ("حذف المشروع؟", "Delete project?"),
        ["dlg.proj.msg"]     = ("سيُحذف المشروع «{0}» نهائيّاً. لا يمكن التراجع عن هذا.", "“{0}” will be permanently deleted. This can’t be undone."),
        ["dlg.proj.msgN"]    = ("سيُحذف المشروع «{0}» و{1} من أوامره نهائيّاً. لا يمكن التراجع عن هذا.", "“{0}” and its {1} command(s) will be permanently deleted. This can’t be undone."),
        ["dlg.tag.title"]    = ("حذف التاك؟", "Delete tag?"),
        ["dlg.tag.msg"]      = ("سيُحذف التاك «{0}» نهائيّاً. لا يمكن التراجع.", "“{0}” will be permanently deleted. This can’t be undone."),
        ["dlg.tag.msgN"]     = ("سيُحذف التاك «{0}» ويُفكّ من {1} مشروعاً (لا تُحذَف المشاريع). لا يمكن التراجع.", "“{0}” will be deleted and detached from {1} project(s) (projects are kept). This can’t be undone."),
        ["dlg.profile.title"]     = ("حذف البروفايل؟", "Delete profile?"),
        ["dlg.profile.msg"]       = ("سيُحذف البروفايل «{0}» نهائيّاً. لا يمكن التراجع.", "“{0}” will be permanently deleted. This can’t be undone."),
        ["dlg.profile.pickTitle"] = ("بروفايلات الصدفات", "Shell profiles"),
        ["dlg.profile.pickMsg"]   = ("اختر بروفايلاً مخصّصاً لحذفه.", "Select a custom profile to delete."),

        // الإدارة (عمليّات + خدمات + منافذ)
        ["srv.mgmt.memory"]    = ("🧠 الذاكرة", "🧠 Memory"),
        ["srv.mgmt.cpu"]       = ("⚙ الحِمل / الأنوية", "⚙ Load / cores"),
        ["srv.mgmt.swap"]      = ("💾 التبديل (Swap)", "💾 Swap"),
        ["srv.mgmt.topMem"]    = ("أعلى مستهلكي الذاكرة", "Top memory consumers"),
        ["srv.mgmt.topCpu"]    = ("أعلى مستهلكي المعالج", "Top CPU consumers"),
        ["srv.mgmt.memApps"]   = ("تطبيقات", "Apps"),
        ["srv.mgmt.memCache"]  = ("كاش/مؤقّت", "Cache"),
        ["srv.mgmt.memFree"]   = ("حرّ", "Free"),
        ["srv.mgmt.memAvail"]  = ("متاح", "Available"),
        ["ctx.options"]        = ("خيارات", "Options"),

        // ===== قائمة التبويب (النافذة) وقائمة المشروع =====
        ["tabctx.rename"]      = ("إعادة تسمية التبويب…", "Rename tab…"),
        ["tabctx.duplicate"]   = ("تكرار التبويب", "Duplicate tab"),
        ["tabctx.detach"]      = ("فصل إلى نافذة مستقلّة", "Detach to new window"),
        ["tabctx.openExplorer"] = ("فتح في المستكشف", "Open in Explorer"),
        ["explorer.notfound"]  = ("مجلّد العمل غير موجود.", "Working directory not found."),
        ["tabctx.copyTitle"]   = ("نسخ عنوان التبويب", "Copy tab title"),
        ["tabctx.copyCwd"]     = ("نسخ مجلّد العمل", "Copy working directory"),
        ["tabctx.moveStart"]   = ("نقل للأمام", "Move tab forward"),
        ["tabctx.moveEnd"]     = ("نقل للخلف", "Move tab back"),
        ["tabctx.close"]       = ("إغلاق التبويب", "Close tab"),
        ["tabctx.closeOthers"] = ("إغلاق التبويبات الأخرى", "Close other tabs"),
        ["tabctx.closeAfter"]  = ("إغلاق ما بعده", "Close tabs after this"),
        ["tabctx.rename.msg"]  = ("اسم التبويب الجديد:", "New tab name:"),
        ["tabctx.color.none"]  = ("بلا لون", "No color"),

        ["projctx.openNew"]    = ("فتح في تبويب جديد", "Open in new tab"),
        ["projctx.copyName"]   = ("نسخ اسم المشروع", "Copy project name"),
        ["projctx.copyPath"]   = ("نسخ الباث", "Copy path"),
        ["projctx.explorer"]   = ("فتح في المستكشف", "Reveal in File Explorer"),
        ["projctx.duplicate"]  = ("تكرار المشروع", "Duplicate project"),
        ["projctx.rename"]     = ("إعادة تسمية…", "Rename…"),
        ["projctx.rename.msg"] = ("اسم المشروع الجديد:", "New project name:"),
        ["projctx.color"]      = ("لون المشروع", "Project color"),
        ["projctx.copy.suffix"]= ("نسخة", "copy"),

        // تقرير الأخطاء غير المتوقّعة (CrashReporter)
        ["crash.title"]    = ("حدث خطأ غير متوقّع", "Unexpected error"),
        ["crash.message"]  = ("حصل خطأ غير متوقّع وحُفِظت تفاصيله في ملفّ سجلّ.\nيمكنك متابعة العمل، لكن يُستحسن إعادة تشغيل التطبيق إن تكرّر.",
                              "An unexpected error occurred and the details were saved to a log file.\nYou can keep working, but restarting is advised if it repeats."),
        ["crash.fatal"]    = ("حدث خطأ أوقف التطبيق. حُفِظت التفاصيل في ملفّ السجلّ.",
                              "An error stopped the app. The details were saved to the log file."),
        ["crash.openLog"]  = ("فتح ملفّ السجلّ", "Open log file"),
        ["crash.continue"] = ("متابعة", "Continue"),

        // إشعار انتهاء أمر طويل (يظهر حين تكون النافذة غير نشطة)
        ["notify.cmdDone"]   = ("انتهى الأمر", "Command finished"),
        ["notify.cmdFailed"] = ("فشل الأمر", "Command failed"),

        // التحديث من إصدارات GitHub (Velopack): فحص صامت ← إشعار ← موافقة ← تنزيل ← إعادة تشغيل
        ["update.available"]    = ("تحديث متوفّر", "Update available"),
        ["update.availableMsg"] = ("النسخة {0} جاهزة للتنزيل (الحاليّة {1}). اضغط هنا للتحديث.",
                                   "Version {0} is ready to download (you have {1}). Click here to update."),
        ["update.confirmTitle"] = ("تحديث إلى النسخة {0}؟", "Update to version {0}?"),
        ["update.confirmMsg"]   = ("سيُنزَّل التحديث في الخلفيّة، ثمّ نسألك عن إعادة التشغيل.",
                                   "The update will download in the background, then we'll ask about restarting."),
        ["update.now"]          = ("تحديث الآن", "Update now"),
        ["update.later"]        = ("لاحقاً", "Later"),
        ["update.downloading"]  = ("تنزيل التحديث", "Downloading update"),
        ["update.restartTitle"] = ("النسخة {0} جاهزة", "Version {0} is ready"),
        ["update.restartMsg"]   = ("أُنزِّل التحديث. إعادة التشغيل الآن تفتح النسخة الجديدة مباشرةً؛ وإلّا يُطبَّق عند إغلاق التطبيق.",
                                   "The update was downloaded. Restarting now opens the new version immediately; otherwise it is applied when you close the app."),
        ["update.restartNow"]   = ("أعد التشغيل الآن", "Restart now"),
        ["update.ready"]    = ("تحديث جاهز", "Update ready"),
        ["update.readyMsg"] = ("نُزِّلت النسخة {0} — تُطبَّق تلقائيّاً عند إعادة تشغيل التطبيق.",
                               "Version {0} was downloaded — it will be applied when you restart the app."),
        ["update.upToDate"]     = ("أنت على أحدث نسخة", "You're up to date"),
        ["update.upToDateMsg"]  = ("النسخة {0} هي الأحدث.", "Version {0} is the latest."),
        ["update.checking"]     = ("جارٍ الفحص…", "Checking…"),
        ["update.failed"]       = ("تعذّر التحديث", "Update failed"),
        ["update.failedMsg"]    = ("تعذّر الوصول إلى إصدارات GitHub. تحقّق من الاتّصال وأعد المحاولة.",
                                   "Couldn't reach GitHub releases. Check your connection and try again."),
        ["update.check"]        = ("تحقّق من التحديثات", "Check for updates"),
        ["tip.update"]          = ("تحديث متوفّر", "Update available"),
        ["srv.mgmt.swapLabel"] = ("التبديل (Swap)", "Swap"),
        ["srv.mgmt.processes"] = ("العمليّات", "Processes"),
        ["srv.mgmt.services"]  = ("الخدمات", "Services"),
        ["srv.mgmt.ports"]     = ("المنافذ المُنصِتة", "Listening ports"),
        ["srv.mgmt.kill"]      = ("إنهاء العمليّة", "Kill process"),
        ["srv.mgmt.kill9"]     = ("إنهاء إجباريّ (-9)", "Force kill (-9)"),
        ["srv.mgmt.killConfirm"] = ("إنهاء العمليّة رقم", "Kill process"),
        ["srv.mgmt.killed"]    = ("تمّ إنهاء العمليّة", "Process killed"),
        ["srv.mgmt.start"]     = ("تشغيل", "Start"),
        ["srv.mgmt.stop"]      = ("إيقاف", "Stop"),
        ["srv.mgmt.restart"]   = ("إعادة تشغيل", "Restart"),
        ["srv.files.scan"]     = ("أكبر الملفّات", "Largest files"),
        ["srv.files.search"]   = ("بحث في النتائج…", "Search results…"),
        ["srv.files.filesWord"]= ("ملفّ", "files"),
        ["srv.files.export"]   = ("تصدير CSV", "Export CSV"),
        ["srv.col.name"]       = ("الاسم", "Name"),
        ["srv.col.ext"]        = ("الامتداد", "Extension"),
        ["srv.col.modified"]   = ("التعديل", "Modified"),
        ["srv.col.path"]       = ("المسار", "Path"),
        ["srv.file.download"]  = ("تنزيل", "Download"),
        ["srv.file.viewLog"]   = ("عرض (آخر 1000 سطر)", "View (last 1000 lines)"),
        ["srv.file.rename"]    = ("إعادة تسمية", "Rename"),
        ["srv.file.copyPath"]  = ("نسخ المسار", "Copy path"),
        ["srv.file.whichContainer"] = ("اعرف الحاوية", "Which container?"),
        ["srv.docker.resolving"] = ("جارٍ تحديد الحاوية…", "Identifying container…"),
        ["srv.docker.notDocker"] = ("هذا الملفّ ليس داخل طبقة overlay2 ولا حجم Docker.", "This file is not inside a Docker overlay2 layer or volume."),
        ["srv.docker.overlayLayer"] = ("طبقة overlay2", "overlay2 layer"),
        ["srv.docker.volume"]  = ("حجم Docker", "Docker volume"),
        ["srv.docker.noOwner"] = ("لم يُعثر على حاوية تملك طبقة الكتابة هذه (قد تكون طبقة صورة أساس مشتركة، أو Docker غير متوفّر/بلا صلاحية).", "No container owns this writable layer (it may be a shared base-image layer, or Docker is unavailable)."),
        ["srv.docker.noVolOwner"] = ("لا حاوية تُركّب هذا الحجم حاليّاً.", "No container currently mounts this volume."),
        ["srv.docker.image"]   = ("الصورة", "Image"),
        ["srv.docker.status"]  = ("الحالة", "Status"),
        ["srv.docker.rwLayer"] = ("الملفّ في طبقة الكتابة لهذه الحاوية (المالك الحصريّ).", "File is in this container's writable layer (exclusive owner)."),
        ["srv.docker.mounted"] = ("حجم مُركَّب في هذه الحاوية.", "Volume mounted in this container."),
        ["srv.docker.ownerTitle"] = ("الحاوية المالكة", "Owning container"),
        ["srv.docker.copyName"] = ("نسخ الاسم", "Copy name"),
        ["srv.docker.copyId"]  = ("نسخ المعرّف", "Copy ID"),
        ["srv.docker.enter"]   = ("فتح الحاوية", "Open container"),
        ["srv.docker.sshMissing"] = ("عميل OpenSSH (ssh.exe) غير متوفّر على هذا الجهاز. فعّل «OpenSSH Client» من إعدادات ويندوز (الميزات الاختياريّة) ثمّ أعد المحاولة.", "The OpenSSH client (ssh.exe) is not available on this machine. Enable 'OpenSSH Client' from Windows optional features and try again."),
        ["srv.file.delete"]    = ("حذف", "Delete"),
        ["srv.file.deleteTitle"] = ("حذف الملفّ", "Delete file"),
        ["srv.file.deleteConfirm"] = ("سيُحذف هذا الملفّ نهائيّاً. لا يمكن التراجع.", "This file will be permanently deleted. This can’t be undone."),
        ["srv.file.downloadOk"]= ("تمّ التنزيل بنجاح.", "Download complete."),
        ["srv.file.downloadFail"] = ("تعذّر التنزيل:", "Download failed:"),
        ["srv.file.opFail"]    = ("فشلت العمليّة:", "Operation failed:"),
        ["srv.file.loading"]   = ("جارٍ الفحص…", "Scanning…"),
        ["srv.log.search"]     = ("بحث في السجلّ (Enter)…", "Search log (Enter)…"),
        ["srv.toast.copied"]   = ("تمّ نسخ المسار", "Path copied"),
        ["srv.folder.filesIn"] = ("ملفّات:", "Files in:"),
        ["srv.folder.noFiles"] = ("لا ملفّات مباشرة في هذا المجلّد", "No files directly in this folder"),
        ["srv.folder.detailHint"] = ("اضغط مجلّداً لعرض ملفّاته", "Click a folder to view its files"),
        ["srv.font.smaller"]   = ("تصغير خطّ التفاصيل", "Smaller detail font"),
        ["srv.font.larger"]    = ("تكبير خطّ التفاصيل", "Larger detail font"),
        ["srv.font.tip"]       = ("حجم خطّ التفاصيل", "Detail font size"),
        ["srv.dl.downloading"] = ("تنزيل", "Downloading"),
        ["srv.dl.cancelled"]   = ("أُلغي التنزيل", "Download cancelled"),
        ["srv.file.deleted"]   = ("تمّ الحذف", "Deleted"),
        ["srv.file.renamed"]   = ("تمّت إعادة التسمية", "Renamed"),
        ["srv.files.empty"]    = ("لا ملفّات", "No files"),
        ["srv.files.noMatch"]  = ("لا نتائج للبحث", "No matches"),

        // قائمة أدوات النظام (زرّ الأدوات في الواجهة الرئيسة)
        ["tools.menu"]         = ("أدوات النظام", "System tools"),
        ["tools.serverMonitor"]= ("مراقب الخوادم", "Server Monitor"),

        // ===== مساعد الـ AI: لوحة الدردشة =====
        ["ai.panel.title"]     = ("مساعد الذكاء الاصطناعي", "AI assistant"),
        ["ai.panel.ask"]       = ("اسأل عن أيّ شيء…", "Ask anything…"),
        ["ai.panel.send"]      = ("إرسال", "Send"),
        ["ai.panel.stop"]      = ("إيقاف", "Stop"),
        ["ai.panel.clear"]     = ("محادثة جديدة", "New conversation"),
        ["ai.panel.copyAll"]   = ("نسخ المحادثة", "Copy conversation"),
        ["ai.panel.copyCode"]  = ("نسخ", "Copy"),
        ["ai.panel.copied"]    = ("نُسخ", "Copied"),
        ["ai.panel.thinking"]  = ("يفكّر…", "Thinking…"),
        ["ai.panel.you"]       = ("أنت", "You"),
        ["ai.panel.closeWarn"] = ("هناك ردّ قيد الاستقبال. إغلاق التبويب سيلغيه.",
                                  "A reply is still streaming. Closing this tab will cancel it."),

        // بطاقة أوّل تشغيل: ثلاثة مسارات لا معالج متعدّد الخطوات.
        ["ai.first.title"]     = ("اربط مزوّداً لتبدأ", "Connect a provider to start"),
        ["ai.first.hint"]      = ("اختر مساراً — يمكن تغييره لاحقاً من الإعدادات.",
                                  "Pick a path — you can change it later in settings."),
        ["ai.first.cloud"]     = ("أدخل مفتاح مزوّد", "Enter a provider key"),
        ["ai.first.gateway"]   = ("مفتاح OpenRouter واحد لعشرات النماذج",
                                  "One OpenRouter key for dozens of models"),
        ["ai.first.local"]     = ("Ollama محلّي — بلا مفتاح", "Local Ollama — no key"),
        ["ai.first.localFound"]= ("وجدنا Ollama يعمل على جهازك", "Found Ollama running on this machine"),
        ["ai.first.localMiss"] = ("لم نجد Ollama يعمل الآن", "Ollama isn't running right now"),
        ["ai.first.later"]     = ("لاحقاً", "Later"),

        // ===== إعدادات الـ AI =====
        ["ai.set.title"]       = ("الذكاء الاصطناعي", "AI"),
        ["ai.set.provider"]    = ("المزوّد", "Provider"),
        ["ai.set.model"]       = ("النموذج", "Model"),
        ["ai.set.refreshModels"]=("تحديث القائمة", "Refresh list"),
        ["ai.set.key"]         = ("مفتاح الـ API", "API key"),
        ["ai.set.getKey"]      = ("احصل على مفتاح", "Get a key"),
        ["ai.set.test"]        = ("اختبار الاتّصال", "Test connection"),
        ["ai.set.testing"]     = ("جارٍ الاختبار…", "Testing…"),
        ["ai.set.baseUrl"]     = ("عنوان الخدمة (اختياريّ)", "Service URL (optional)"),
        ["ai.set.keyStored"]   = ("مفتاح محفوظ ومُعمّى على هذا الجهاز", "Key stored and encrypted on this device"),
        ["ai.set.keyMissing"]  = ("لا مفتاح بعد", "No key yet"),
        ["ai.set.keyReentry"]  = ("المفتاح مُعمّى على جهاز آخر — أعد إدخاله هنا",
                                  "Key was encrypted on another device — re-enter it here"),
        ["ai.set.noKeyNeeded"] = ("لا يحتاج مفتاحاً", "No key needed"),
        ["ai.set.learning"]    = ("التعلّم من استعمالي (محلّيّاً)", "Learn from my usage (locally)"),
        ["ai.set.learningHint"]= ("يبني قاعدة معرفة محلّيّة لترتيب الاقتراحات. لا يُرسَل شيء خارج جهازك.",
                                  "Builds a local knowledge base to rank suggestions. Nothing leaves your device."),
        ["ai.set.ambient"]     = ("إرسال سياق التبويب مع الدردشة", "Send tab context with chat"),
        ["ai.set.preview"]     = ("راجع قبل الإرسال", "Review before sending"),
        ["ai.set.quiet"]       = ("وضع هادئ (بلا رقاقات اقتراح)", "Quiet mode (no suggestion chips)"),

        // ===== أخطاء المزوّدين: رسالة بشريّة + إجراء =====
        ["ai.err.auth"]        = ("المفتاح غير صالح أو منتهي.", "The API key is invalid or expired."),
        ["ai.err.quota"]       = ("نفد رصيد الحساب أو حصّته لدى المزوّد.",
                                  "The account is out of credit or quota."),
        ["ai.err.rate"]        = ("تجاوزت حدّ المعدّل — انتظر قليلاً ثمّ أعد المحاولة.",
                                  "Rate limit reached — wait a moment and retry."),
        ["ai.err.rateWait"]    = ("تجاوزت حدّ المعدّل — أعد المحاولة بعد {0} ثانية.",
                                  "Rate limit reached — retry in {0}s."),
        ["ai.err.context"]     = ("السياق أطول ممّا يقبله هذا النموذج.",
                                  "The context is longer than this model accepts."),
        ["ai.err.model"]       = ("النموذج المختار غير متاح لدى هذا المزوّد.",
                                  "The selected model isn't available from this provider."),
        ["ai.err.network"]     = ("تعذّر الوصول إلى المزوّد — تحقّق من الاتّصال.",
                                  "Couldn't reach the provider — check your connection."),
        ["ai.err.timeout"]     = ("انتهت المهلة بلا استجابة.", "Timed out with no response."),
        ["ai.err.canceled"]    = ("أُلغي الطلب.", "Request cancelled."),
        ["ai.err.provider"]    = ("ردّ المزوّد بخطأ.", "The provider returned an error."),
        ["ai.err.noProvider"]  = ("لم يُربط مزوّد بعد — افتح الإعدادات لإضافة مفتاح.",
                                  "No provider connected yet — open settings to add a key."),
        // ===== معاينة ما سيُرسَل =====
        ["ai.prev.title"]      = ("هذا ما سيُرسَل", "This is what will be sent"),
        ["ai.prev.redacted"]   = ("حُجبت {0} عناصر — راجع قبل الإرسال",
                                  "{0} item(s) redacted — review before sending"),
        ["ai.prev.notSecret"]  = ("ليس سرّاً", "Not a secret"),
        ["ai.prev.allowed"]    = ("لن يُحجب", "Won't redact"),
        ["ai.prev.send"]       = ("أرسل", "Send"),
        ["ai.prev.cancel"]     = ("إلغاء", "Cancel"),

        // ===== أفعال السياق =====
        ["ai.ctx.explain"]     = ("اشرح هذا", "Explain this"),
        ["ai.ctx.explainFail"] = ("اشرح آخر خطأ", "Explain last error"),
        ["ai.ctx.fixFail"]     = ("أصلح آخر أمر فاشل", "Fix last failed command"),
        ["ai.ctx.toCommand"]   = ("حوّل إلى أمر", "Turn into a command"),
        ["ai.ctx.noFailed"]    = ("لا يوجد أمر فاشل بعد — يحتاج تكامل الصدفة (OSC 133).",
                                  "No failed command yet — needs shell integration (OSC 133)."),
        ["ai.ctx.askExplain"]  = ("اشرح ما حدث هنا وكيف أصلحه.",
                                  "Explain what happened here and how to fix it."),
        ["ai.ctx.askFix"]      = ("اقترح أمراً واحداً يصلح هذا الفشل. ضعه في كتلة كود.",
                                  "Suggest one command that fixes this failure. Put it in a code block."),
        ["ai.ctx.insert"]      = ("أدرج في سطر الإدخال", "Insert into the prompt"),
        ["ai.ctx.risky"]       = ("⚠ أمر خطر — راجعه قبل التنفيذ", "⚠ Risky command — review before running"),
        ["ai.ctx.inserted"]    = ("أُدرج — اضغط Enter لتنفيذه بنفسك",
                                  "Inserted — press Enter to run it yourself"),

        // ===== نافذة «ذاكرة التطبيق» =====
        ["ai.mem.title"]       = ("ذاكرة التطبيق", "App memory"),
        ["ai.mem.open"]        = ("ذاكرة التطبيق", "App memory"),
        ["ai.mem.subtitle"]    = ("كلّ ما تعلّمه التطبيق عن استعمالك — محفوظ على هذا الجهاز وحده، ولا يُرسَل إلى أيّ خدمة.",
                                  "Everything the app learned about your usage — stored on this device only, never sent anywhere."),
        ["ai.mem.stats"]       = ("{0} قالب أمر · نسبة قبول الاقتراحات {1} · حجم القاعدة {2} م.ب",
                                  "{0} command templates · suggestion acceptance {1} · database {2} MB"),
        ["ai.mem.tabCommands"] = ("أوامرك المتكرّرة", "Your frequent commands"),
        ["ai.mem.tabErrors"]   = ("الأخطاء وحلولها", "Errors and fixes"),
        ["ai.mem.tabSuggestions"] = ("سجلّ الاقتراحات", "Suggestion log"),
        ["ai.mem.colCommand"]  = ("القالب", "Template"),
        ["ai.mem.colRuns"]     = ("مرّات", "Runs"),
        ["ai.mem.colOutcome"]  = ("النتيجة", "Outcome"),
        ["ai.mem.colActions"]  = ("إجراءات", "Actions"),
        ["ai.mem.colError"]    = ("الخطأ", "Error"),
        ["ai.mem.colSolution"] = ("الحلّ المحفوظ", "Saved fix"),
        ["ai.mem.colSeen"]     = ("تكرار", "Seen"),
        ["ai.mem.colSuggestion"] = ("الاقتراح", "Suggestion"),
        ["ai.mem.colKind"]     = ("النوع", "Kind"),
        ["ai.mem.colVerdict"]  = ("القرار", "Verdict"),
        ["ai.mem.outcome"]     = ("{0} نجاح · {1} فشل", "{0} ok · {1} failed"),
        ["ai.mem.pin"]         = ("تثبيت", "Pin"),
        ["ai.mem.unpin"]       = ("إلغاء التثبيت", "Unpin"),
        ["ai.mem.ban"]         = ("حظر", "Ban"),
        ["ai.mem.unban"]       = ("رفع الحظر", "Unban"),
        ["ai.mem.delete"]      = ("حذف", "Delete"),
        ["ai.mem.noSolution"]  = ("لا حلّ محفوظ بعد", "No saved fix yet"),
        ["ai.mem.accepted"]    = ("قُبِل", "Accepted"),
        ["ai.mem.rejected"]    = ("رُفِض", "Rejected"),
        ["ai.mem.pending"]     = ("معلّق", "Pending"),
        ["ai.mem.tabProfile"]  = ("ملفّك التعريفيّ", "Your profile"),
        ["ai.mem.profileEmpty"]= ("لا ملفّ بعد — يحتاج التطبيق بضعة أوامر متكرّرة قبل أن يستنتج شيئاً يستحقّ الإرسال.",
                                  "No profile yet — the app needs a few repeated commands before it has anything worth sending."),
        ["ai.mem.clearAll"]    = ("امسح كل شيء", "Erase everything"),
        ["ai.mem.clearConfirm"]= ("سيُحذف كلّ ما تعلّمه التطبيق: قوالب الأوامر وعدّاداتها، والأخطاء وحلولها، وسجلّ الاقتراحات. لا يمكن التراجع.",
                                  "This erases everything the app learned: command templates and counters, errors and fixes, and the suggestion log. This cannot be undone."),
        ["ai.mem.empty"]       = ("لا شيء هنا بعد. مع استعمالك للتيرمنال سيتعلّم التطبيق أوامرك المتكرّرة وأخطاءك الشائعة، فيرتّب الاقتراحات ويعرض حلولاً سبق أن قبلتها — كلّه محلّيّاً وبلا اتّصال.",
                                  "Nothing here yet. As you use the terminal the app learns your frequent commands and common errors, then ranks suggestions and recalls fixes you accepted — all locally, no connection needed."),

        // ===== رقاقة الخطأ =====
        ["ai.chip.explain"]    = ("اشرح هذا الخطأ؟", "Explain this error?"),
        ["ai.chip.seenBefore"] = ("رأيت هذا من قبل — الحل السابق", "Seen before — previous fix"),
        ["ai.chip.dismiss"]    = ("إخفاء", "Dismiss"),

        ["ai.act.settings"]    = ("افتح الإعدادات", "Open settings"),
        ["ai.act.retry"]       = ("أعد المحاولة", "Retry"),
        ["ai.act.billing"]     = ("صفحة الفوترة", "Billing page"),
        ["ai.act.trim"]        = ("قلّص السياق", "Trim context"),
    };
}
